/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.RegistrationPanels;

import DataConfiguration.Enterprise;
import DataConfiguration.Network;
import DataConfiguration.Organization;
import Directories.EnterpriseDirectory;
import java.util.Random;
import ui.RegistrationPanels.*;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.UserAccountManagement.UserAccountDirectory;
import model.client.Person;
import model.organization.AidReceipent.AidReceipentDirectory;
import model.organization.AidReceipent.AidReceipentProfile;
import model.organization.VolunteerManagement.VolunteerDirectory;
import model.organization.VolunteerManagement.VolunteerProfile;

/**
 *
 * @author rugvedgundawar
 */
public class AidReceipentRegistrationJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    Network network;
    /**
     * Creates new form AidReceipentRegistration
     */
    public AidReceipentRegistrationJPanel(JPanel userProcessContainer,Network network) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.network = network;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lblAidReceiptName = new javax.swing.JLabel();
        txtAidReceiptName = new javax.swing.JTextField();
        lblAidReceiptEmail = new javax.swing.JLabel();
        txtAidReceiptEmail = new javax.swing.JTextField();
        lblAidReceiptContact = new javax.swing.JLabel();
        txtAidReceiptContact = new javax.swing.JTextField();
        lblAidReceiptAddress = new javax.swing.JLabel();
        txtAidReceiptAddress = new javax.swing.JTextField();
        btnAidReciptRegister = new javax.swing.JButton();
        lblAidReceiptAge = new javax.swing.JLabel();
        txtAidReceiptAge = new javax.swing.JTextField();
        lblAidReceiptPassword = new javax.swing.JLabel();
        lblAidReceiptConfirmPassword = new javax.swing.JLabel();
        txtAidReceiptPassword = new javax.swing.JPasswordField();
        txtAidReceiptConfirmPassword = new javax.swing.JPasswordField();

        jLabel4.setText("Email Address:");

        jTextField3.setText("jTextField1");

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registration");

        lblAidReceiptName.setText("Name:");

        lblAidReceiptEmail.setText("Email Address:");

        lblAidReceiptContact.setText("Phone Number:");

        lblAidReceiptAddress.setText("Address:");

        btnAidReciptRegister.setText("Register");
        btnAidReciptRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAidReciptRegisterActionPerformed(evt);
            }
        });

        lblAidReceiptAge.setText("Age:");

        lblAidReceiptPassword.setText("Password:");

        lblAidReceiptConfirmPassword.setText("Confirm Password:");

        txtAidReceiptPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAidReceiptPasswordActionPerformed(evt);
            }
        });

        txtAidReceiptConfirmPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAidReceiptConfirmPasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblAidReceiptConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAidReceiptConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblAidReceiptName, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAidReceiptName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblAidReceiptEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAidReceiptEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblAidReceiptContact, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblAidReceiptAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblAidReceiptAge)
                            .addComponent(lblAidReceiptPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtAidReceiptAge, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(txtAidReceiptAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(txtAidReceiptContact, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(btnAidReciptRegister, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(txtAidReceiptPassword))))
                .addContainerGap(165, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAidReciptRegister, lblAidReceiptAddress, lblAidReceiptAge, lblAidReceiptConfirmPassword, lblAidReceiptContact, lblAidReceiptEmail, lblAidReceiptName, lblAidReceiptPassword, txtAidReceiptAddress, txtAidReceiptAge, txtAidReceiptConfirmPassword, txtAidReceiptContact, txtAidReceiptEmail, txtAidReceiptName, txtAidReceiptPassword});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAidReceiptName)
                    .addComponent(txtAidReceiptName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAidReceiptEmail)
                    .addComponent(txtAidReceiptEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAidReceiptContact)
                    .addComponent(txtAidReceiptContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAidReceiptAge)
                    .addComponent(txtAidReceiptAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAidReceiptAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAidReceiptAddress))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAidReceiptPassword)
                    .addComponent(txtAidReceiptPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAidReceiptConfirmPassword)
                    .addComponent(txtAidReceiptConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(btnAidReciptRegister)
                .addGap(39, 39, 39))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAidReciptRegister, lblAidReceiptAddress, lblAidReceiptAge, lblAidReceiptConfirmPassword, lblAidReceiptContact, lblAidReceiptEmail, lblAidReceiptName, lblAidReceiptPassword, txtAidReceiptAddress, txtAidReceiptAge, txtAidReceiptConfirmPassword, txtAidReceiptContact, txtAidReceiptEmail, txtAidReceiptName, txtAidReceiptPassword});

    }// </editor-fold>//GEN-END:initComponents

    private void btnAidReciptRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAidReciptRegisterActionPerformed
        // TODO add your handling code here:
        
        String name = txtAidReceiptName.getText().trim();
        String email = txtAidReceiptEmail.getText().trim();
        String phone = txtAidReceiptContact.getText().trim();
        String ageText = txtAidReceiptAge.getText().trim();
        String address = txtAidReceiptAddress.getText().trim();
        char[] password = txtAidReceiptPassword.getPassword();
        char[] confirmPassword = txtAidReceiptConfirmPassword.getPassword();
        
        if (name.isEmpty() || email.isEmpty() || phone.isEmpty() || ageText.isEmpty() || address.isEmpty()|| password==null || confirmPassword==null) {
                    JOptionPane.showMessageDialog(this, "All fields must be filled.", "Validation Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }

                if (!email.matches("^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+$")) {
                    JOptionPane.showMessageDialog(this, "Invalid email format.", "Validation Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }

                if (!phone.matches("\\d{10}")) {
                    JOptionPane.showMessageDialog(this, "Phone number must be 10 digits.", "Validation Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }

                try {
                    int age = Integer.parseInt(ageText);
                    if (age <= 0 || age > 120) {
                        JOptionPane.showMessageDialog(this, "Age must be a positive number and less than 120.", "Validation Error", JOptionPane.ERROR_MESSAGE);
                        return;
                    }
                } catch (NumberFormatException ex) {
                    JOptionPane.showMessageDialog(this, "Age must be a numeric value.", "Validation Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                if(!(String.valueOf(password).equals(String.valueOf(confirmPassword))))
                {
                    JOptionPane.showMessageDialog(null, "Passwords don't match","Warning",JOptionPane.WARNING_MESSAGE);
                    return;
                }

//                // Success message
//                JOptionPane.showMessageDialog(this, "Registration successful!", "Success", JOptionPane.INFORMATION_MESSAGE);
                Random random = new Random();
        EnterpriseDirectory enterpriseDirectory = network.getEnterpriseDirectory();
        Enterprise enterprise = enterpriseDirectory.findEnterprise("Public Service Enterprise");
        Organization organization = enterprise.getOrganizationDirectory().findOrganization("Receipient Registration");
        UserAccountDirectory userAccountDirectory = network.getUserAccountDirectory();
        AidReceipentDirectory aidReceipentDirectory = organization.getAidReceipentDirectory();
        Person pp1 = new Person(String.valueOf(random.nextInt(90000) + 10000));
        AidReceipentProfile ap = aidReceipentDirectory.newAidReceipentProfile(pp1, name, email,Integer.parseInt(phone), Integer.parseInt(ageText), "password");
        userAccountDirectory.newUserAccount(ap,name , "password");
        
        System.out.println("Volunteer profile created: " + ap.getPerson().getPersonId());
        
        JOptionPane.showMessageDialog(null, "Registration Succesful","Success",JOptionPane.INFORMATION_MESSAGE);                                          
    }//GEN-LAST:event_btnAidReciptRegisterActionPerformed

    private void txtAidReceiptPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAidReceiptPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAidReceiptPasswordActionPerformed

    private void txtAidReceiptConfirmPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAidReceiptConfirmPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAidReceiptConfirmPasswordActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAidReciptRegister;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel lblAidReceiptAddress;
    private javax.swing.JLabel lblAidReceiptAge;
    private javax.swing.JLabel lblAidReceiptConfirmPassword;
    private javax.swing.JLabel lblAidReceiptContact;
    private javax.swing.JLabel lblAidReceiptEmail;
    private javax.swing.JLabel lblAidReceiptName;
    private javax.swing.JLabel lblAidReceiptPassword;
    private javax.swing.JTextField txtAidReceiptAddress;
    private javax.swing.JTextField txtAidReceiptAge;
    private javax.swing.JPasswordField txtAidReceiptConfirmPassword;
    private javax.swing.JTextField txtAidReceiptContact;
    private javax.swing.JTextField txtAidReceiptEmail;
    private javax.swing.JTextField txtAidReceiptName;
    private javax.swing.JPasswordField txtAidReceiptPassword;
    // End of variables declaration//GEN-END:variables
}
