/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.RegistrationPanels;

import DataConfiguration.Enterprise;
import DataConfiguration.Network;
import DataConfiguration.Organization;
import Directories.EnterpriseDirectory;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.UserAccountManagement.UserAccountDirectory;
import model.client.Person;
import model.organization.DonationManagement.Donor;
import model.organization.DonationManagement.DonorDirectory;

/**
 *
 * @author sahar
 */
public class DonorRegistrationJPanel extends javax.swing.JPanel {
    JPanel userProcessContainer;
    Network network;
    /**
     * Creates new form DonorRegistrationJPanel
     */
    public DonorRegistrationJPanel(JPanel userProcessContainer,Network network) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.network = network;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAidReceiptEmail = new javax.swing.JLabel();
        txtDonorPassword = new javax.swing.JPasswordField();
        txtDonorEmail = new javax.swing.JTextField();
        txtDonorConfirmPassword = new javax.swing.JPasswordField();
        lblAidReceiptContact = new javax.swing.JLabel();
        txtDonorContact = new javax.swing.JTextField();
        btnDonorRegister = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblAidReceiptName = new javax.swing.JLabel();
        lblAidReceiptPassword = new javax.swing.JLabel();
        txtDonorName = new javax.swing.JTextField();
        lblAidReceiptConfirmPassword = new javax.swing.JLabel();

        lblAidReceiptEmail.setText("Email Address:");

        txtDonorPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDonorPasswordActionPerformed(evt);
            }
        });

        txtDonorConfirmPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDonorConfirmPasswordActionPerformed(evt);
            }
        });

        lblAidReceiptContact.setText("Phone Number:");

        btnDonorRegister.setText("Register");
        btnDonorRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDonorRegisterActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Donor Registration");

        lblAidReceiptName.setText("Name:");

        lblAidReceiptPassword.setText("Password:");

        lblAidReceiptConfirmPassword.setText("Confirm Password:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblAidReceiptPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDonorPassword))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblAidReceiptConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDonorConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblAidReceiptName, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDonorName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblAidReceiptEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDonorEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblAidReceiptContact, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDonorContact, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(btnDonorRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(131, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(213, 213, 213)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAidReceiptName)
                    .addComponent(txtDonorName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAidReceiptEmail)
                    .addComponent(txtDonorEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAidReceiptContact)
                    .addComponent(txtDonorContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAidReceiptPassword)
                    .addComponent(txtDonorPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAidReceiptConfirmPassword)
                    .addComponent(txtDonorConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(btnDonorRegister)
                .addContainerGap(118, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtDonorPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDonorPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDonorPasswordActionPerformed

    private void txtDonorConfirmPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDonorConfirmPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDonorConfirmPasswordActionPerformed

    private void btnDonorRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDonorRegisterActionPerformed
        // TODO add your handling code here:

        String name = txtDonorName.getText().trim();
        String email = txtDonorEmail.getText().trim();
        String phone = txtDonorContact.getText().trim();
        char[] password = txtDonorPassword.getPassword();
        char[] confirmPassword = txtDonorConfirmPassword.getPassword();

        if (name.isEmpty() || email.isEmpty() || phone.isEmpty() || password==null || confirmPassword==null) {
            JOptionPane.showMessageDialog(this, "All fields must be filled.", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!email.matches("^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+$")) {
            JOptionPane.showMessageDialog(this, "Invalid email format.", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!phone.matches("\\d{10}")) {
            JOptionPane.showMessageDialog(this, "Phone number must be 10 digits.", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if(!(String.valueOf(password).equals(String.valueOf(confirmPassword))))
        {
            JOptionPane.showMessageDialog(null, "Passwords don't match","Warning",JOptionPane.WARNING_MESSAGE);
            return;
        }

        //                // Success message
        //                JOptionPane.showMessageDialog(this, "Registration successful!", "Success", JOptionPane.INFORMATION_MESSAGE);
        Random random = new Random();
        EnterpriseDirectory enterpriseDirectory = network.getEnterpriseDirectory();
        Enterprise enterprise = enterpriseDirectory.findEnterprise("Community Support Enterprise");
        Organization organization = enterprise.getOrganizationDirectory().findOrganization("Donation Management");
        UserAccountDirectory userAccountDirectory = network.getUserAccountDirectory();
        DonorDirectory donorDirectory = organization.getDonerDirectory();
        Person dnrp = new Person(String.valueOf(random.nextInt(90000) + 10000));
        Donor dnr = donorDirectory.newDonorProfile(dnrp, name, email,Integer.parseInt(phone), String.valueOf(password));
        userAccountDirectory.newUserAccount(dnr,name , String.valueOf(password));

        System.out.println("Volunteer profile created: " + dnr.getPerson().getPersonId());

        JOptionPane.showMessageDialog(null, "Registration Succesful","Success",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnDonorRegisterActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDonorRegister;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAidReceiptConfirmPassword;
    private javax.swing.JLabel lblAidReceiptContact;
    private javax.swing.JLabel lblAidReceiptEmail;
    private javax.swing.JLabel lblAidReceiptName;
    private javax.swing.JLabel lblAidReceiptPassword;
    private javax.swing.JPasswordField txtDonorConfirmPassword;
    private javax.swing.JTextField txtDonorContact;
    private javax.swing.JTextField txtDonorEmail;
    private javax.swing.JTextField txtDonorName;
    private javax.swing.JPasswordField txtDonorPassword;
    // End of variables declaration//GEN-END:variables
}
