/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.DataAnalyst;

import AidRequest.Resource;
import Campaign.Campaign;
import DataConfiguration.Network;
import DataConfiguration.Organization;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.organization.AidReceipent.AidReceipentProfile;
import model.organization.VolunteerManagement.VolunteerDirectory;
import model.organization.VolunteerManagement.VolunteerProfile;

/**
 *
 * @author rugvedgundawar
 */
public class SeeReportJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    Network network;
    Organization organization;
    Resource resource;
    /**
     * Creates new form SeeReportJPanel
     */
    public SeeReportJPanel(JPanel userProcessContainer, Network network, Organization organization) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.network = network;
        this.organization = organization;
        
        populateVolunteerTable();
        populateReceipientsTable();
        populateCampaignTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVolunteerData = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtVolunteerCount = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtReceipientsCount = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblReceipientsData = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtCampaignCount = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblCampaignData = new javax.swing.JTable();

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Report");

        tblVolunteerData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name", "Email", "Age", "Total Hours"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblVolunteerData);
        if (tblVolunteerData.getColumnModel().getColumnCount() > 0) {
            tblVolunteerData.getColumnModel().getColumn(0).setResizable(false);
            tblVolunteerData.getColumnModel().getColumn(1).setResizable(false);
            tblVolunteerData.getColumnModel().getColumn(2).setResizable(false);
            tblVolunteerData.getColumnModel().getColumn(3).setResizable(false);
            tblVolunteerData.getColumnModel().getColumn(3).setHeaderValue("Total Hours");
        }

        jLabel2.setText("Volunteer Data");

        jLabel3.setText("Total Volunteers");

        jLabel4.setText("Receipents Data");

        jLabel5.setText("Total Receipients:");

        tblReceipientsData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Name", "Email", "Age"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblReceipientsData);
        if (tblReceipientsData.getColumnModel().getColumnCount() > 0) {
            tblReceipientsData.getColumnModel().getColumn(0).setResizable(false);
            tblReceipientsData.getColumnModel().getColumn(1).setResizable(false);
            tblReceipientsData.getColumnModel().getColumn(2).setResizable(false);
        }

        jLabel6.setText("Campaign Data");

        jLabel7.setText("Total Campaigns:");

        tblCampaignData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title", "Description", "Location", "Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblCampaignData);
        if (tblCampaignData.getColumnModel().getColumnCount() > 0) {
            tblCampaignData.getColumnModel().getColumn(0).setResizable(false);
            tblCampaignData.getColumnModel().getColumn(1).setResizable(false);
            tblCampaignData.getColumnModel().getColumn(2).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(txtVolunteerCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(txtReceipientsCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(txtCampaignCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6))
                        .addGap(0, 50, Short.MAX_VALUE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel3, jLabel5, jLabel7, txtCampaignCount, txtReceipientsCount, txtVolunteerCount});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtVolunteerCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtReceipientsCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtCampaignCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(124, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel3, jLabel5, jLabel7, txtCampaignCount, txtReceipientsCount, txtVolunteerCount});

    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblCampaignData;
    private javax.swing.JTable tblReceipientsData;
    private javax.swing.JTable tblVolunteerData;
    private javax.swing.JTextField txtCampaignCount;
    private javax.swing.JTextField txtReceipientsCount;
    private javax.swing.JTextField txtVolunteerCount;
    // End of variables declaration//GEN-END:variables

    private void populateVolunteerTable() {
        DefaultTableModel tableModel = (DefaultTableModel) tblVolunteerData.getModel();
        tableModel.setRowCount(0);
        organization=network.getEnterpriseDirectory().findEnterprise("Non-Profit Enterprise").getOrganizationDirectory().findOrganization("Volunteer Management");
        for (VolunteerProfile vp : organization.getVolunteerDirectory().getVolunteerList()) {
                Object[] row ={
                            vp.getName(),
                            vp.getEmail(),
                            vp.getAge(),
                            vp.getTotalHours()
                        };
                        tableModel.addRow(row);        }
        txtVolunteerCount.setText(Integer.toString(organization.getVolunteerDirectory().getVolunteerList().size()));
    }

    private void populateReceipientsTable() {
        DefaultTableModel tableModel = (DefaultTableModel) tblReceipientsData.getModel();
        tableModel.setRowCount(0);
        organization = network.getEnterpriseDirectory().findEnterprise("Public Service Enterprise").getOrganizationDirectory().findOrganization("Receipient Registration");
        for (AidReceipentProfile vp : organization.getAidReceipentDirectory().getAidReceipentsList()) {
                Object[] row ={
                            vp.getName(),
                            vp.getEmail(),
                            vp.getAge()
                        };
                        tableModel.addRow(row);        }
        txtReceipientsCount.setText(Integer.toString(organization.getAidReceipentDirectory().getAidReceipentsList().size()));
    }

    private void populateCampaignTable() {
        DefaultTableModel tableModel = (DefaultTableModel) tblCampaignData.getModel();
        tableModel.setRowCount(0);
        organization = network.getEnterpriseDirectory().findEnterprise("Corporate Donors Enterprise").getOrganizationDirectory().findOrganization("Campaign Management");
        if (organization == null) {
    System.err.println("Organization 'Campaign Management' not found!");
    return; // Exit the method to avoid further errors
}
        if (organization.getCampaigns() == null) {
    System.err.println("No campaigns found for organization: " + organization.getName());
    return; // Exit the method
}

        for (Campaign c : organization.getCampaigns()) {
                Object[] row ={
                            c.getTitle(),
                            c.getDescription(),
                            c.getLocation(),
                            c.getDate()
                        };
                        tableModel.addRow(row);        }
        txtReceipientsCount.setText(Integer.toString(organization.getCampaigns().size()));
    }
}
