/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.ProfileComponents;

import DataConfiguration.Network;
import DataConfiguration.Organization;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.organization.CamapignManagement.Campaign;
import model.organization.CamapignManagement.CampaignDirectory;

/**
 *
 * @author Sarthak
 */
public class ViewCampaignsJPanel extends javax.swing.JPanel {

    JPanel CampaignOrganizerWorkArea;
    Network network;
    /**
     * Creates new form ViewCampaignsJPanel
     */
    public ViewCampaignsJPanel(JPanel CampaignOrganizerWorkArea, Network network) {
        initComponents();
        this.CampaignOrganizerWorkArea = CampaignOrganizerWorkArea;
        this.network = network;
        populateCampaignTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblCampaigns = new javax.swing.JTable();
        btnDeleteCampaign = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        tblCampaigns.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Location", "Description", "From", "To"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCampaigns);

        btnDeleteCampaign.setText("Delete");
        btnDeleteCampaign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteCampaignActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Sora ExtraBold", 1, 18)); // NOI18N
        jLabel1.setText("Campaigns:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDeleteCampaign, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 785, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(153, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(btnDeleteCampaign, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(114, 114, 114))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteCampaignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteCampaignActionPerformed
        // TODO add your handling code here:
        
        Organization org = network.getEnterpriseDirectory()
                          .findEnterprise("Corporate Donors Enterprise")
                          .getOrganizationDirectory()
                          .findOrganization("Campaign Management");
        CampaignDirectory cd = org.getCampaignDirectory();
        
        int selectedCampaign = tblCampaigns.getSelectedRow();
        if(selectedCampaign<0){
            JOptionPane.showMessageDialog(this, "Please select campaign", "Warning",JOptionPane.WARNING_MESSAGE);
            return;
        }
        //Getting table model
        DefaultTableModel model = (DefaultTableModel) tblCampaigns.getModel();
        //Getting selected row from the table
        Campaign selectedCampaignRecord = (Campaign) model.getValueAt(selectedCampaign,0);
        cd.removeCampaign(selectedCampaignRecord);
        model.setRowCount(0);
        populateCampaignTable();
        JOptionPane.showMessageDialog(this, "Campaign deleted", "Sucess",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnDeleteCampaignActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeleteCampaign;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCampaigns;
    // End of variables declaration//GEN-END:variables

    private void populateCampaignTable() {
        Organization org = network.getEnterpriseDirectory()
                          .findEnterprise("Corporate Donors Enterprise")
                          .getOrganizationDirectory()
                          .findOrganization("Campaign Management");
        CampaignDirectory cd = org.getCampaignDirectory();
        ArrayList<Campaign> campaignList = cd.getAllCampaigns();        
        if (campaignList.isEmpty()) {
            return;
        }
        
        DefaultTableModel model = (DefaultTableModel) tblCampaigns.getModel();
        model.setRowCount(0); // Clear the table

        for (Campaign camp : campaignList) { 
                Object[] row = new Object[5];
                row[0] = camp;
                row[1] = camp.getLocation();    
                row[2] = camp.getDescription();  
                row[3] = camp.getFromDate();  
                row[4] = camp.getToDate();  

                model.addRow(row);          

        }
    }
}
