/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.ProfileComponents;

import DataConfiguration.Network;
import DataConfiguration.Organization;
import SMSFeature.SmsSender;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.organization.VolunteerManagement.VolunteerDirectory;
import model.organization.VolunteerManagement.VolunteerProfile;
import com.twilio.Twilio;
import com.twilio.rest.api.v2010.account.Message;
import com.twilio.type.PhoneNumber;

/**
 *
 * @author Sarthak
 */
public class VolunteerCoordinatorDashboard extends javax.swing.JPanel {

    JPanel volunteerCoordinatorWorkArea;
    Network network;
    /**
     * Creates new form VolunteerCoordinatorDashboard
     */
    public VolunteerCoordinatorDashboard(JPanel volunteerCoordinatorWorkArea,Network network) {
        initComponents();
        this.volunteerCoordinatorWorkArea = volunteerCoordinatorWorkArea;
        this.network = network;
        populateVolunteersTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVolunteerInfo = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        txtMessage = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnAssignTask = new javax.swing.JButton();
        btnDeleteVolunteer = new javax.swing.JButton();
        txtTaskTextArea = new javax.swing.JTextField();
        txtSendSMS = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Volunteer List");

        tblVolunteerInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Email", "Phone", "Tasks", "Total Hours"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblVolunteerInfo);

        jPanel1.setBackground(new java.awt.Color(221, 246, 226));

        jLabel2.setFont(new java.awt.Font("Sora Medium", 0, 12)); // NOI18N
        jLabel2.setText("Message:");

        btnAssignTask.setFont(new java.awt.Font("Sora Medium", 0, 12)); // NOI18N
        btnAssignTask.setText("Assign Task");
        btnAssignTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignTaskActionPerformed(evt);
            }
        });

        btnDeleteVolunteer.setBackground(new java.awt.Color(255, 30, 0));
        btnDeleteVolunteer.setFont(new java.awt.Font("Sora Medium", 0, 12)); // NOI18N
        btnDeleteVolunteer.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteVolunteer.setText("Delete Volunteer");
        btnDeleteVolunteer.setBorder(null);
        btnDeleteVolunteer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteVolunteerActionPerformed(evt);
            }
        });

        txtSendSMS.setFont(new java.awt.Font("Sora Medium", 0, 12)); // NOI18N
        txtSendSMS.setText("Send SMS");
        txtSendSMS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSendSMSActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnDeleteVolunteer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAssignTask, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(txtTaskTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtSendSMS))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAssignTask, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTaskTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSendSMS))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeleteVolunteer, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(26, 26, 26)
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(136, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(101, 101, 101))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAssignTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignTaskActionPerformed
        // TODO add your handling code here:
        String task = txtTaskTextArea.getText().trim();
        if(task.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please enter task", "Warning",JOptionPane.WARNING_MESSAGE);
            return;
        }
        int selectedVolunteer = tblVolunteerInfo.getSelectedRow();
        if(selectedVolunteer<0){
            JOptionPane.showMessageDialog(this, "Please select volunteer", "Warning",JOptionPane.WARNING_MESSAGE);
            return;
        }
        //Getting table model
        DefaultTableModel model = (DefaultTableModel) tblVolunteerInfo.getModel();
        //Getting selected row from the table
        VolunteerProfile selectedVolunteerRecord = (VolunteerProfile) model.getValueAt(selectedVolunteer,0);
        selectedVolunteerRecord.assignTask(task);
        selectedVolunteerRecord.incrementHours();
        model.setRowCount(0);
        populateVolunteersTable();
        JOptionPane.showMessageDialog(this, "Task Assigned successfully", "Sucsess",JOptionPane.INFORMATION_MESSAGE);
        return;
    }//GEN-LAST:event_btnAssignTaskActionPerformed

    private void btnDeleteVolunteerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteVolunteerActionPerformed
        // TODO add your handling code here:
        Organization org = network.getEnterpriseDirectory().findEnterprise("Non-Profit Enterprise").getOrganizationDirectory().findOrganization("Volunteer Management");
        VolunteerDirectory vd = org.getVolunteerDirectory();
        int selectedVolunteer = tblVolunteerInfo.getSelectedRow();
        if(selectedVolunteer<0){
            JOptionPane.showMessageDialog(this, "Please select volunteer", "Warning",JOptionPane.WARNING_MESSAGE);
            return;
        }
        DefaultTableModel model = (DefaultTableModel) tblVolunteerInfo.getModel();
        //Getting selected row from the table
        VolunteerProfile selectedVolunteerRecord = (VolunteerProfile) model.getValueAt(selectedVolunteer,0);
        vd.removeVolunteer(selectedVolunteerRecord);
        model.setRowCount(0);
        populateVolunteersTable();
        JOptionPane.showMessageDialog(this, "Volunteer Profile deleted!", "Sucsess",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnDeleteVolunteerActionPerformed

    private void txtSendSMSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSendSMSActionPerformed
        // TODO add your handling code here:
        String message = txtMessage.getText().trim();
        
        int selectedVolunteer = tblVolunteerInfo.getSelectedRow();
        if(selectedVolunteer<0){
            JOptionPane.showMessageDialog(this, "Please select volunteer", "Warning",JOptionPane.WARNING_MESSAGE);
            return;
        }
        if(message.isBlank())
        {
            JOptionPane.showMessageDialog(this, "Include message to send sms", "Warning",JOptionPane.WARNING_MESSAGE);
            return;
        }
        DefaultTableModel model = (DefaultTableModel) tblVolunteerInfo.getModel();
        //Getting selected row from the table
        VolunteerProfile vp = (VolunteerProfile) model.getValueAt(selectedVolunteer,0);
        SmsSender sms = new SmsSender();
        sms.sendSMS(vp.getPhoneNumber(),message) ;
        JOptionPane.showMessageDialog(this, "Message sent to volunteer successfully", "Sucsess",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_txtSendSMSActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssignTask;
    private javax.swing.JButton btnDeleteVolunteer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblVolunteerInfo;
    private javax.swing.JTextField txtMessage;
    private javax.swing.JButton txtSendSMS;
    private javax.swing.JTextField txtTaskTextArea;
    // End of variables declaration//GEN-END:variables

    private void populateVolunteersTable() {
        Organization org = network.getEnterpriseDirectory().findEnterprise("Non-Profit Enterprise").getOrganizationDirectory().findOrganization("Volunteer Management");
        org.getVolunteerDirectory().getVolunteerList();
        ArrayList<VolunteerProfile> volunteersList = org.getVolunteerDirectory().getVolunteerList();
        
        if (volunteersList.isEmpty()) {
            return;
        }

        for (VolunteerProfile vp : volunteersList) { 
                Object[] row = new Object[5];
                row[0] = vp;
                row[1] = vp.getEmail();
                row[2] = vp.getPhoneNumber();
                row[3] = vp.getTasks().isEmpty() ?  "No Tasks" : vp.getTasks().toString().replace("[", "").replace("]", "");
                row[4] = vp.getTotalHours();

                ((DefaultTableModel) tblVolunteerInfo.getModel()).addRow(row);          

        }
    }
}
