/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.ProfileComponents;

import DataConfiguration.Network;
import DataConfiguration.Organization;
import java.util.ArrayList;
import javax.swing.JPanel;
import model.organization.VolunteerManagement.VolunteerProfile;

/**
 *
 * @author Sarthak
 */
public class VolunteerStatsJPanel extends javax.swing.JPanel {

    JPanel volunteerWorkArea;
    Organization org;
    /**
     * Creates new form VolunteerStatsJPanel
     */
    public VolunteerStatsJPanel(JPanel volunteerWorkArea,Organization org) {
        initComponents();
        this.volunteerWorkArea = volunteerWorkArea;
        this.org = org;
        populateVolunteerStats();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtTotalVolunteers = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtTotalVolunteersHoursAssigned = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtMaleVolunteers = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtFemaleVolunteers = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        jLabel1.setText("Total Volunteers:");

        txtTotalVolunteers.setEditable(false);

        jLabel2.setText("Total Volunteer Task Hours Assigned: ");

        txtTotalVolunteersHoursAssigned.setEditable(false);

        jLabel3.setText("Total MALE volunteers:");

        txtMaleVolunteers.setEditable(false);

        jLabel4.setText("Total FEMALE  volunteers:");

        txtFemaleVolunteers.setEditable(false);

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setText("Statistics");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTotalVolunteers, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTotalVolunteersHoursAssigned, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMaleVolunteers, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFemaleVolunteers, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(jLabel5)))
                .addContainerGap(177, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtFemaleVolunteers, txtMaleVolunteers, txtTotalVolunteers, txtTotalVolunteersHoursAssigned});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabel5)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotalVolunteers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotalVolunteersHoursAssigned, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaleVolunteers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFemaleVolunteers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(99, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtFemaleVolunteers, txtMaleVolunteers, txtTotalVolunteers, txtTotalVolunteersHoursAssigned});

    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtFemaleVolunteers;
    private javax.swing.JTextField txtMaleVolunteers;
    private javax.swing.JTextField txtTotalVolunteers;
    private javax.swing.JTextField txtTotalVolunteersHoursAssigned;
    // End of variables declaration//GEN-END:variables

    private void populateVolunteerStats() {
        ArrayList<VolunteerProfile> list = org.getVolunteerDirectory().getVolunteerList();
        int taskAssignedHours = 0;
        int maleVolunteers = 0;
        int femaleVolunteers = 0;
        int totalVolunteers = org.getVolunteerDirectory().getVolunteerList().size();
        txtTotalVolunteers.setText(Integer.toString(totalVolunteers));
        for(VolunteerProfile vp : list){
            taskAssignedHours+=vp.getTotalHours();
            maleVolunteers+= vp.getGender().equalsIgnoreCase("MALE") ? 1 : 0;
            femaleVolunteers+= vp.getGender().equalsIgnoreCase("FEMALE") ? 1 : 0;
        }
        txtTotalVolunteersHoursAssigned.setText(Integer.toString(taskAssignedHours));
        txtMaleVolunteers.setText(Integer.toString(maleVolunteers));
        txtFemaleVolunteers.setText(Integer.toString(femaleVolunteers));        
    }
}
