/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.ProfileComponents;

import DataConfiguration.Network;
import DataConfiguration.Organization;
import java.util.ArrayList;
import javax.swing.JPanel;
import model.organization.VolunteerManagement.VolunteerProfile;

/**
 *
 * @author Sarthak
 */
public class VolunteerStatsJPanel extends javax.swing.JPanel {

    JPanel volunteerWorkArea;
    Organization org;
    /**
     * Creates new form VolunteerStatsJPanel
     */
    public VolunteerStatsJPanel(JPanel volunteerWorkArea,Organization org) {
        initComponents();
        this.volunteerWorkArea = volunteerWorkArea;
        this.org = org;
        populateVolunteerStats();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtMaleVolunteers = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtFemaleVolunteers = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtTotalVolunteers = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtTotalVolunteersHoursAssigned = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Sora ExtraBold", 1, 18)); // NOI18N
        jLabel5.setText("Statistics");

        jPanel1.setBackground(new java.awt.Color(221, 246, 226));

        txtMaleVolunteers.setEditable(false);
        txtMaleVolunteers.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Sora Light", 0, 12)); // NOI18N
        jLabel4.setText("Total FEMALE  volunteers:");

        txtFemaleVolunteers.setEditable(false);
        txtFemaleVolunteers.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Sora Light", 0, 12)); // NOI18N
        jLabel1.setText("Total Volunteers:");

        txtTotalVolunteers.setEditable(false);
        txtTotalVolunteers.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Sora Light", 0, 12)); // NOI18N
        jLabel2.setText("Total Volunteer Task Hours Assigned: ");

        txtTotalVolunteersHoursAssigned.setEditable(false);
        txtTotalVolunteersHoursAssigned.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Sora Light", 0, 12)); // NOI18N
        jLabel3.setText("Total MALE volunteers:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtMaleVolunteers, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtFemaleVolunteers, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11))
                    .addComponent(txtTotalVolunteersHoursAssigned, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotalVolunteers, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addContainerGap(115, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTotalVolunteers, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTotalVolunteersHoursAssigned, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMaleVolunteers, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFemaleVolunteers, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(jLabel5)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(132, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtFemaleVolunteers;
    private javax.swing.JTextField txtMaleVolunteers;
    private javax.swing.JTextField txtTotalVolunteers;
    private javax.swing.JTextField txtTotalVolunteersHoursAssigned;
    // End of variables declaration//GEN-END:variables

    private void populateVolunteerStats() {
        ArrayList<VolunteerProfile> list = org.getVolunteerDirectory().getVolunteerList();
        int taskAssignedHours = 0;
        int maleVolunteers = 0;
        int femaleVolunteers = 0;
        int totalVolunteers = org.getVolunteerDirectory().getVolunteerList().size();
        txtTotalVolunteers.setText(Integer.toString(totalVolunteers));
        for(VolunteerProfile vp : list){
            taskAssignedHours+=vp.getTotalHours();
            maleVolunteers+= vp.getGender().equalsIgnoreCase("MALE") ? 1 : 0;
            femaleVolunteers+= vp.getGender().equalsIgnoreCase("FEMALE") ? 1 : 0;
        }
        txtTotalVolunteersHoursAssigned.setText(Integer.toString(taskAssignedHours));
        txtMaleVolunteers.setText(Integer.toString(maleVolunteers));
        txtFemaleVolunteers.setText(Integer.toString(femaleVolunteers));        
    }
}
