/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.ProfileComponents;

import DataConfiguration.Network;
import DataConfiguration.Organization;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.organization.VolunteerManagement.VolunteerProfile;
import model.organization.VolunteerManagement.VolunteerTaskStatus;

/**
 *
 * @author Sarthak
 */
public class VolunteerCoordinatorDashboard extends javax.swing.JPanel {

    JPanel volunteerCoordinatorWorkArea;
    Network network;
    /**
     * Creates new form VolunteerCoordinatorDashboard
     */
    public VolunteerCoordinatorDashboard(JPanel volunteerCoordinatorWorkArea,Network network) {
        initComponents();
        this.volunteerCoordinatorWorkArea = volunteerCoordinatorWorkArea;
        this.network = network;
        populateVolunteersTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVolunteerInfo = new javax.swing.JTable();
        btnAssignTask = new javax.swing.JButton();
        btnDeleteVolunteer = new javax.swing.JButton();
        txtTaskTextArea = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Volunteer List");

        tblVolunteerInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Email", "Tasks", "Total Hours"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblVolunteerInfo);

        btnAssignTask.setText("Assign Task");
        btnAssignTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignTaskActionPerformed(evt);
            }
        });

        btnDeleteVolunteer.setText("Delete Volunteer");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(293, 293, 293)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(119, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnDeleteVolunteer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAssignTask, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(39, 39, 39)
                        .addComponent(txtTaskTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(88, 88, 88))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAssignTask)
                    .addComponent(txtTaskTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnDeleteVolunteer)
                .addContainerGap(40, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAssignTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignTaskActionPerformed
        // TODO add your handling code here:
        String task = txtTaskTextArea.getText().trim();
        if(task.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please enter task", "Warning",JOptionPane.WARNING_MESSAGE);
            return;
        }
        int selectedVolunteer = tblVolunteerInfo.getSelectedRow();
        if(selectedVolunteer<0){
            JOptionPane.showMessageDialog(this, "Please select volunteer", "Warning",JOptionPane.WARNING_MESSAGE);
            return;
        }
        //Getting table model
        DefaultTableModel model = (DefaultTableModel) tblVolunteerInfo.getModel();
        //Getting selected row from the table
        VolunteerProfile selectedVolunteerRecord = (VolunteerProfile) model.getValueAt(selectedVolunteer,0);
        selectedVolunteerRecord.assignTask(task);
        selectedVolunteerRecord.incrementHours();
        model.setRowCount(0);
        populateVolunteersTable();
        JOptionPane.showMessageDialog(this, "Task Assigned successfully", "Sucsess",JOptionPane.INFORMATION_MESSAGE);
        return;
    }//GEN-LAST:event_btnAssignTaskActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssignTask;
    private javax.swing.JButton btnDeleteVolunteer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblVolunteerInfo;
    private javax.swing.JTextField txtTaskTextArea;
    // End of variables declaration//GEN-END:variables

    private void populateVolunteersTable() {
        Organization org = network.getEnterpriseDirectory().findEnterprise("Non-Profit Enterprise").getOrganizationDirectory().findOrganization("Volunteer Management");
        org.getVolunteerDirectory().getVolunteerList();
        ArrayList<VolunteerProfile> volunteersList = org.getVolunteerDirectory().getVolunteerList();
        
        if (volunteersList.isEmpty()) {
            return;
        }

        for (VolunteerProfile vp : volunteersList) { 
                Object[] row = new Object[4];
                row[0] = vp;
                row[1] = vp.getEmail();
                row[2] = vp.getTasks().isEmpty() ?  "No Tasks" : vp.getTasks().toString().replace("[", "").replace("]", "");
                row[3] = vp.getTotalHours();

                ((DefaultTableModel) tblVolunteerInfo.getModel()).addRow(row);          

        }
    }
}
