/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.AidReceipient;

import DataConfiguration.Organization;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.organization.AidReceipent.AidReceipentProfile;
import model.organization.AidReceipent.AidRequest;
import model.organization.AidReceipent.AidRequestDirectory;

/**
 *
 * @author rugvedgundawar
 */
public class AidReceipentNewRequestJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    AidRequestDirectory aidRequestDirectory;
    AidReceipentProfile aidReceipentProfile;
    Organization organization;
    /**
     * Creates new form AidReceipentNewRequestJPanel
     */
    public AidReceipentNewRequestJPanel(JPanel userProcessContainer,AidReceipentProfile aidReceipentProfile, Organization organization) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.aidReceipentProfile = aidReceipentProfile;
        this.organization = organization;
        
        txtRequestorName.setText(aidReceipentProfile.getName());
    }

    /** 
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        btnAidRequest = new javax.swing.JButton();
        lblAidAmountNeeded = new javax.swing.JLabel();
        txtAidAmountNeeded = new javax.swing.JTextField();
        lblAidRequestId = new javax.swing.JLabel();
        txtAidRequestID = new javax.swing.JTextField();
        lblAidRequestorName = new javax.swing.JLabel();
        txtRequestorName = new javax.swing.JTextField();
        lblAidReason = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAidReason = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        jLabel4.setText("Request ID:");

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(221, 246, 226));

        btnAidRequest.setBackground(new java.awt.Color(0, 153, 102));
        btnAidRequest.setFont(new java.awt.Font("Sora Medium", 0, 14)); // NOI18N
        btnAidRequest.setForeground(new java.awt.Color(255, 255, 255));
        btnAidRequest.setText("Request");
        btnAidRequest.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAidRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAidRequestActionPerformed(evt);
            }
        });

        lblAidAmountNeeded.setText("Amount Needed:");

        txtAidAmountNeeded.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAidAmountNeededActionPerformed(evt);
            }
        });

        lblAidRequestId.setText("Request ID:");

        txtAidRequestID.setEnabled(false);

        lblAidRequestorName.setText("Requestor Name:");

        lblAidReason.setText("Reason");

        txtAidReason.setColumns(20);
        txtAidReason.setRows(5);
        jScrollPane1.setViewportView(txtAidReason);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtAidRequestID, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAidRequestId, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRequestorName, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAidRequestorName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAidReason, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAidAmountNeeded, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAidAmountNeeded, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(btnAidRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblAidAmountNeeded, lblAidReason, lblAidRequestId, lblAidRequestorName});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(lblAidRequestId)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtAidRequestID, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblAidRequestorName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtRequestorName, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblAidReason)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblAidAmountNeeded)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAidAmountNeeded, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btnAidRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblAidAmountNeeded, lblAidReason, lblAidRequestId, lblAidRequestorName});

        jLabel1.setFont(new java.awt.Font("Sora ExtraBold", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("AID REQUEST");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(129, 129, 129))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(124, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAidRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAidRequestActionPerformed
        // TODO add your handling code here:
        String requestorName = txtRequestorName.getText().trim();
        String amountNeededText = txtAidAmountNeeded.getText().trim();
        String reason = txtAidReason.getText().trim();

        // Validation
        if (requestorName.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Requestor Name must not be empty.", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (amountNeededText.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Amount Needed must not be empty.", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        double amountNeeded;
        try {
            amountNeeded = Double.parseDouble(amountNeededText);
            if (amountNeeded <= 0) {
                JOptionPane.showMessageDialog(this, "Amount Needed must be a positive number.", "Validation Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Amount Needed must be a valid number.", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (reason.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Reason must not be empty.", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        aidRequestDirectory = organization.getAidRequestDirectory();
        aidRequestDirectory.addAidRequest(requestorName,Double.parseDouble(amountNeededText),reason,aidReceipentProfile);
        
        // Simulate a successful submission
        JOptionPane.showMessageDialog(this, "Request submitted successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);

        // Reset fields
        txtRequestorName.setText("");
        txtAidAmountNeeded.setText("");
        txtAidReason.setText("");
    }//GEN-LAST:event_btnAidRequestActionPerformed

    private void txtAidAmountNeededActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAidAmountNeededActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAidAmountNeededActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAidRequest;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel lblAidAmountNeeded;
    private javax.swing.JLabel lblAidReason;
    private javax.swing.JLabel lblAidRequestId;
    private javax.swing.JLabel lblAidRequestorName;
    private javax.swing.JTextField txtAidAmountNeeded;
    private javax.swing.JTextArea txtAidReason;
    private javax.swing.JTextField txtAidRequestID;
    private javax.swing.JTextField txtRequestorName;
    // End of variables declaration//GEN-END:variables
}
