/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.AidReceipient;

import DataConfiguration.Organization;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.organization.AidReceipent.AidReceipentProfile;
import model.organization.AidReceipent.AidRequest;
import model.organization.AidReceipent.AidRequestDirectory;

/**
 *
 * @author rugvedgundawar
 */
public class AidReceipentNewRequestJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    AidRequestDirectory aidRequestDirectory;
    AidReceipentProfile aidReceipentProfile;
    Organization organization;
    /**
     * Creates new form AidReceipentNewRequestJPanel
     */
    public AidReceipentNewRequestJPanel(JPanel userProcessContainer,AidReceipentProfile aidReceipentProfile, Organization organization) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.aidReceipentProfile = aidReceipentProfile;
        this.organization = organization;
        
        txtRequestorName.setText(aidReceipentProfile.getName());
    }

    /** 
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lblAidRequestId = new javax.swing.JLabel();
        txtAidRequestID = new javax.swing.JTextField();
        lblAidRequestorName = new javax.swing.JLabel();
        txtRequestorName = new javax.swing.JTextField();
        lblAidReason = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAidReason = new javax.swing.JTextArea();
        btnAidRequest = new javax.swing.JButton();
        lblAidAmountNeeded = new javax.swing.JLabel();
        txtAidAmountNeeded = new javax.swing.JTextField();

        jLabel4.setText("Request ID:");

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("AID REQUEST");

        lblAidRequestId.setText("Request ID:");

        txtAidRequestID.setEnabled(false);

        lblAidRequestorName.setText("Requestor Name:");

        lblAidReason.setText("Reason");

        txtAidReason.setColumns(20);
        txtAidReason.setRows(5);
        jScrollPane1.setViewportView(txtAidReason);

        btnAidRequest.setText("Request");
        btnAidRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAidRequestActionPerformed(evt);
            }
        });

        lblAidAmountNeeded.setText("Amount Needed:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(182, 182, 182)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAidRequestId, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAidRequestorName, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAidAmountNeeded, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAidReason, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAidAmountNeeded, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRequestorName, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAidRequestID, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnAidRequest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(147, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAidRequest, jScrollPane1, lblAidAmountNeeded, lblAidReason, lblAidRequestId, lblAidRequestorName, txtAidAmountNeeded, txtAidRequestID, txtRequestorName});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAidRequestId)
                    .addComponent(txtAidRequestID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAidRequestorName)
                    .addComponent(txtRequestorName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAidReason)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAidAmountNeeded)
                    .addComponent(txtAidAmountNeeded, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAidRequest)
                .addContainerGap(120, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAidRequest, lblAidAmountNeeded, lblAidReason, lblAidRequestId, lblAidRequestorName, txtAidRequestID, txtRequestorName});

    }// </editor-fold>//GEN-END:initComponents

    private void btnAidRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAidRequestActionPerformed
        // TODO add your handling code here:
        String requestorName = txtRequestorName.getText().trim();
        String amountNeededText = txtAidAmountNeeded.getText().trim();
        String reason = txtAidReason.getText().trim();

        // Validation
        if (requestorName.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Requestor Name must not be empty.", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (amountNeededText.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Amount Needed must not be empty.", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        double amountNeeded;
        try {
            amountNeeded = Double.parseDouble(amountNeededText);
            if (amountNeeded <= 0) {
                JOptionPane.showMessageDialog(this, "Amount Needed must be a positive number.", "Validation Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Amount Needed must be a valid number.", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (reason.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Reason must not be empty.", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        aidRequestDirectory = organization.getAidRequestDirectory();
        aidRequestDirectory.addAidRequest(requestorName,Double.parseDouble(amountNeededText),reason,aidReceipentProfile);
        
        // Simulate a successful submission
        JOptionPane.showMessageDialog(this, "Request submitted successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);

        // Reset fields
        txtRequestorName.setText("");
        txtAidAmountNeeded.setText("");
        txtAidReason.setText("");
    }//GEN-LAST:event_btnAidRequestActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAidRequest;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel lblAidAmountNeeded;
    private javax.swing.JLabel lblAidReason;
    private javax.swing.JLabel lblAidRequestId;
    private javax.swing.JLabel lblAidRequestorName;
    private javax.swing.JTextField txtAidAmountNeeded;
    private javax.swing.JTextArea txtAidReason;
    private javax.swing.JTextField txtAidRequestID;
    private javax.swing.JTextField txtRequestorName;
    // End of variables declaration//GEN-END:variables
}
