/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.MainProfilePages;

import DataConfiguration.Network;
import DataConfiguration.Organization;
import java.awt.CardLayout;
import javax.swing.JComboBox;
import javax.swing.JPanel;
import model.admin.AdminProfile;
import ui.Admin.AdminAidCoordinatorJPanel;
import ui.Admin.AdminDataAnalystJPanel;
import ui.Admin.AdminResourcesJPanel;
import ui.Admin.AdminVolunteersJPanel;

/**
 *
 * @author Sarthak
 */
public class AdminProfileJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    Network network;
    Organization organization;
    AdminProfile adminProfile;
    /**
     * Creates new form VolunteerProfileJPanel
     */
    public AdminProfileJPanel(JPanel userProcessContainer, Network network, AdminProfile adminProfile) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.network = network;
        this.adminProfile = adminProfile;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        AdminOptionsJPanel = new javax.swing.JPanel();
        btnLogout = new javax.swing.JButton();
        cmbProfile = new javax.swing.JComboBox<>();
        btnView = new javax.swing.JButton();
        AdminWorkArea = new javax.swing.JPanel();

        jSplitPane1.setDividerLocation(150);

        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        cmbProfile.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aid Coordinator", "Data Analyst", "Volunteers", "Resources" }));
        cmbProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbProfileActionPerformed(evt);
            }
        });

        btnView.setText("View");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AdminOptionsJPanelLayout = new javax.swing.GroupLayout(AdminOptionsJPanel);
        AdminOptionsJPanel.setLayout(AdminOptionsJPanelLayout);
        AdminOptionsJPanelLayout.setHorizontalGroup(
            AdminOptionsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminOptionsJPanelLayout.createSequentialGroup()
                .addGroup(AdminOptionsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AdminOptionsJPanelLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(AdminOptionsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cmbProfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLogout)))
                    .addGroup(AdminOptionsJPanelLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(btnView)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        AdminOptionsJPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnLogout, cmbProfile});

        AdminOptionsJPanelLayout.setVerticalGroup(
            AdminOptionsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminOptionsJPanelLayout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addComponent(cmbProfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnView)
                .addGap(29, 29, 29)
                .addComponent(btnLogout)
                .addContainerGap(213, Short.MAX_VALUE))
        );

        AdminOptionsJPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnLogout, cmbProfile});

        jSplitPane1.setLeftComponent(AdminOptionsJPanel);

        AdminWorkArea.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(AdminWorkArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 682, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this); 
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void cmbProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbProfileActionPerformed
        // TODO add your handling code here:
        String selectedItem = (String) cmbProfile.getSelectedItem();
    }//GEN-LAST:event_cmbProfileActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        String selectedItem = (String) cmbProfile.getSelectedItem();
        
        if(selectedItem.equals("Aid Coordinator")){
            AdminAidCoordinatorJPanel aacJpanel = new AdminAidCoordinatorJPanel(userProcessContainer,network);
            AdminWorkArea.removeAll();
            AdminWorkArea.add(aacJpanel);
            CardLayout layout = (CardLayout) AdminWorkArea.getLayout();
            layout.next(AdminWorkArea);
        }
        if(selectedItem.equals("Data Analyst")){
            AdminDataAnalystJPanel adaJpanel = new AdminDataAnalystJPanel(userProcessContainer,network);
            AdminWorkArea.removeAll();
            AdminWorkArea.add(adaJpanel);
            CardLayout layout = (CardLayout) AdminWorkArea.getLayout();
            layout.next(AdminWorkArea);
        }
        if(selectedItem.equals("Resources")){
            AdminResourcesJPanel arJpanel = new AdminResourcesJPanel(userProcessContainer,network);
            AdminWorkArea.removeAll();
            AdminWorkArea.add(arJpanel);
            CardLayout layout = (CardLayout) AdminWorkArea.getLayout();
            layout.next(AdminWorkArea);
        }
        if(selectedItem.equals("Volunteers")){
            AdminVolunteersJPanel avJpanel = new AdminVolunteersJPanel(userProcessContainer,network);
            AdminWorkArea.removeAll();
            AdminWorkArea.add(avJpanel);
            CardLayout layout = (CardLayout) AdminWorkArea.getLayout();
            layout.next(AdminWorkArea);
        }
    }//GEN-LAST:event_btnViewActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AdminOptionsJPanel;
    private javax.swing.JPanel AdminWorkArea;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnView;
    private javax.swing.JComboBox<String> cmbProfile;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
