/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.MainProfilePages;

/**
 *
 * @author Sarthak
 */
public class AdminProfileJPanel extends javax.swing.JPanel {

    /**
     * Creates new form VolunteerProfileJPanel
     */
    public AdminProfileJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        AdminOptionsJPanel = new javax.swing.JPanel();
        btnResourses = new javax.swing.JButton();
        Campaigns = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        AdminWorkAreaJanel = new javax.swing.JScrollPane();

        jSplitPane1.setDividerLocation(150);

        btnResourses.setText("Resources");

        Campaigns.setText("Campaigns");

        btnLogout.setText("Logout");

        javax.swing.GroupLayout AdminOptionsJPanelLayout = new javax.swing.GroupLayout(AdminOptionsJPanel);
        AdminOptionsJPanel.setLayout(AdminOptionsJPanelLayout);
        AdminOptionsJPanelLayout.setHorizontalGroup(
            AdminOptionsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdminOptionsJPanelLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(AdminOptionsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Campaigns, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnResourses, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(36, 36, 36))
            .addGroup(AdminOptionsJPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(btnLogout)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AdminOptionsJPanelLayout.setVerticalGroup(
            AdminOptionsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminOptionsJPanelLayout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(btnResourses)
                .addGap(30, 30, 30)
                .addComponent(Campaigns)
                .addGap(50, 50, 50)
                .addComponent(btnLogout)
                .addContainerGap(201, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(AdminOptionsJPanel);
        jSplitPane1.setRightComponent(AdminWorkAreaJanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 682, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AdminOptionsJPanel;
    private javax.swing.JScrollPane AdminWorkAreaJanel;
    private javax.swing.JButton Campaigns;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnResourses;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
