/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.MainProfilePages;

import DataConfiguration.Network;
import DataConfiguration.Organization;
import java.awt.CardLayout;
import javax.swing.JPanel;
import model.admin.AidCoordinator;
import model.organization.DonationManagement.Donor;
import ui.AidDistribution.DistributionResourceJPanel;
import ui.DonationManagement.DonationHistoryJPanel;
import ui.LoginPageJPanel;

/**
 *
 * @author Sarthak
 */
public class AidCoordinatorJPanel extends javax.swing.JPanel {
    JPanel userProcessContainer;
    Network network;
    AidCoordinator coord;
    /**
     * Creates new form VolunteerCoordinatorJPanel
     */
    public AidCoordinatorJPanel(JPanel userProcessContainer, Network network, AidCoordinator coord) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.network = network;
        this.coord = coord;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        AidCoordinatorJPanel = new javax.swing.JPanel();
        btnDistribute = new javax.swing.JButton();
        btnAvailableAid = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        AidCoordinatorWorkArea = new javax.swing.JPanel();

        jSplitPane1.setDividerLocation(170);

        btnDistribute.setText("Distribute Resources");
        btnDistribute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDistributeActionPerformed(evt);
            }
        });

        btnAvailableAid.setText("Available Aid");
        btnAvailableAid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvailableAidActionPerformed(evt);
            }
        });

        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AidCoordinatorJPanelLayout = new javax.swing.GroupLayout(AidCoordinatorJPanel);
        AidCoordinatorJPanel.setLayout(AidCoordinatorJPanelLayout);
        AidCoordinatorJPanelLayout.setHorizontalGroup(
            AidCoordinatorJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AidCoordinatorJPanelLayout.createSequentialGroup()
                .addGap(0, 18, Short.MAX_VALUE)
                .addGroup(AidCoordinatorJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AidCoordinatorJPanelLayout.createSequentialGroup()
                        .addGroup(AidCoordinatorJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnDistribute, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAvailableAid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AidCoordinatorJPanelLayout.createSequentialGroup()
                        .addComponent(btnLogout)
                        .addGap(48, 48, 48))))
        );
        AidCoordinatorJPanelLayout.setVerticalGroup(
            AidCoordinatorJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AidCoordinatorJPanelLayout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(btnDistribute)
                .addGap(18, 18, 18)
                .addComponent(btnAvailableAid)
                .addGap(31, 31, 31)
                .addComponent(btnLogout)
                .addContainerGap(200, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(AidCoordinatorJPanel);

        AidCoordinatorWorkArea.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(AidCoordinatorWorkArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 666, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAvailableAidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvailableAidActionPerformed
        // TODO add your handling code here:

//    AidCoordinatorWorkArea.add("DistributionResource", distres);
//    AidCoordinatorWorkArea.revalidate();
//    AidCoordinatorWorkArea.repaint();
//    CardLayout layout = (CardLayout) AidCoordinatorWorkArea.getLayout();
//    layout.show(AidCoordinatorWorkArea, "DistributionResource");
    }//GEN-LAST:event_btnAvailableAidActionPerformed

    private void btnDistributeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDistributeActionPerformed
        // TODO add your handling code here:
                DistributionResourceJPanel distres = new DistributionResourceJPanel(AidCoordinatorWorkArea, network , coord);
        AidCoordinatorWorkArea.removeAll();
        AidCoordinatorWorkArea.add(distres);
        CardLayout layout = (CardLayout) AidCoordinatorWorkArea.getLayout();
        layout.next(AidCoordinatorWorkArea);
    }//GEN-LAST:event_btnDistributeActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        
                // TODO add your handling code here:
            // Clear the current DonorWorkArea
        AidCoordinatorWorkArea.removeAll();

        // Clear the parent container
        userProcessContainer.removeAll();

        // Create and show login panel (or whatever your initial panel is)
        // Assuming your login panel is called LoginJPanel
        LoginPageJPanel loginPanel = new LoginPageJPanel(userProcessContainer, network);
        userProcessContainer.add(loginPanel);

        // Refresh the container
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

        // Optional: Reset any session data
        this.coord = null;
    }//GEN-LAST:event_btnLogoutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AidCoordinatorJPanel;
    private javax.swing.JPanel AidCoordinatorWorkArea;
    private javax.swing.JButton btnAvailableAid;
    private javax.swing.JButton btnDistribute;
    private javax.swing.JButton btnLogout;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
