/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.MainProfilePages;

import DataConfiguration.Network;
import DataConfiguration.Organization;
import java.awt.CardLayout;
import javax.swing.JPanel;
import model.admin.AidCoordinator;
import model.organization.DonationManagement.Donor;
import ui.AidDistribution.DistributionHistoryJPanel;
import ui.AidDistribution.DistributionResourceJPanel;
import ui.DonationManagement.DonationHistoryJPanel;
import ui.LoginPageJPanel;

/**
 *
 * @author Sarthak
 */
public class AidCoordinatorJPanel extends javax.swing.JPanel {
    JPanel userProcessContainer;
    Network network;
    AidCoordinator coord;
    /**
     * Creates new form VolunteerCoordinatorJPanel
     */
    public AidCoordinatorJPanel(JPanel userProcessContainer, Network network, AidCoordinator coord) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.network = network;
        this.coord = coord;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        AidCoordinatorJPanel = new javax.swing.JPanel();
        btnDistribute = new javax.swing.JButton();
        btnAidHistory = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        AidCoordinatorWorkArea = new javax.swing.JPanel();

        jSplitPane1.setDividerLocation(170);

        AidCoordinatorJPanel.setBackground(new java.awt.Color(0, 32, 41));
        AidCoordinatorJPanel.setMinimumSize(new java.awt.Dimension(238, 0));
        AidCoordinatorJPanel.setPreferredSize(new java.awt.Dimension(238, 518));

        btnDistribute.setFont(new java.awt.Font("Sora Medium", 0, 12)); // NOI18N
        btnDistribute.setText("Distribute Resources");
        btnDistribute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDistributeActionPerformed(evt);
            }
        });

        btnAidHistory.setFont(new java.awt.Font("Sora Medium", 0, 12)); // NOI18N
        btnAidHistory.setText("Aid History");
        btnAidHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAidHistoryActionPerformed(evt);
            }
        });

        btnLogout.setBackground(new java.awt.Color(255, 30, 0));
        btnLogout.setFont(new java.awt.Font("Sora SemiBold", 1, 12)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("Logout");
        btnLogout.setBorder(null);
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Sora ExtraBold", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("<html>Aid Coordinator Panel</html>");

        javax.swing.GroupLayout AidCoordinatorJPanelLayout = new javax.swing.GroupLayout(AidCoordinatorJPanel);
        AidCoordinatorJPanel.setLayout(AidCoordinatorJPanelLayout);
        AidCoordinatorJPanelLayout.setHorizontalGroup(
            AidCoordinatorJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AidCoordinatorJPanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(AidCoordinatorJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AidCoordinatorJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnDistribute, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAidHistory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(27, 27, 27))
            .addGroup(AidCoordinatorJPanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        AidCoordinatorJPanelLayout.setVerticalGroup(
            AidCoordinatorJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AidCoordinatorJPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(btnDistribute, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAidHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 150, Short.MAX_VALUE)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        jSplitPane1.setLeftComponent(AidCoordinatorJPanel);

        AidCoordinatorWorkArea.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(AidCoordinatorWorkArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 759, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAidHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAidHistoryActionPerformed
        // TODO add your handling code here:

        DistributionHistoryJPanel hist = new DistributionHistoryJPanel(AidCoordinatorWorkArea, network , coord);
        AidCoordinatorWorkArea.removeAll();
        AidCoordinatorWorkArea.add(hist);
        CardLayout layout = (CardLayout) AidCoordinatorWorkArea.getLayout();
        layout.next(AidCoordinatorWorkArea);
    }//GEN-LAST:event_btnAidHistoryActionPerformed

    private void btnDistributeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDistributeActionPerformed
        // TODO add your handling code here:
        DistributionResourceJPanel distres = new DistributionResourceJPanel(AidCoordinatorWorkArea, network , coord);
        AidCoordinatorWorkArea.removeAll();
        AidCoordinatorWorkArea.add(distres);
        CardLayout layout = (CardLayout) AidCoordinatorWorkArea.getLayout();
        layout.next(AidCoordinatorWorkArea);
    }//GEN-LAST:event_btnDistributeActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        
                // TODO add your handling code here:
            // Clear the current DonorWorkArea
        AidCoordinatorWorkArea.removeAll();

        // Clear the parent container
        userProcessContainer.removeAll();

        // Create and show login panel (or whatever your initial panel is)
        // Assuming your login panel is called LoginJPanel
        LoginPageJPanel loginPanel = new LoginPageJPanel(userProcessContainer, network);
        userProcessContainer.add(loginPanel);

        // Refresh the container
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

        // Optional: Reset any session data
        this.coord = null;
    }//GEN-LAST:event_btnLogoutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AidCoordinatorJPanel;
    private javax.swing.JPanel AidCoordinatorWorkArea;
    private javax.swing.JButton btnAidHistory;
    private javax.swing.JButton btnDistribute;
    private javax.swing.JButton btnLogout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
