/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.MainProfilePages;

import DataConfiguration.Network;
import DataConfiguration.Organization;
import java.awt.CardLayout;
import javax.swing.JPanel;
import model.organization.AidReceipent.AidReceipentProfile;
import model.organization.DonationManagement.Donor;
import ui.AidReceipient.AidReceipentNewRequestJPanel;
import ui.AidReceipient.AidReceipientHistoryJPanel;

/**
 *
 * @author Sarthak
 */
public class AidRecipientJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    Network network;
    AidReceipentProfile aidReceipentProfile;
    Organization organization;
    /**
     * Creates new form VolunteerCoordinatorJPanel
     */
    public AidRecipientJPanel(JPanel userProcessContainer, Network network, AidReceipentProfile aidReceipentProfile, Organization organization) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.network = network;
        this.aidReceipentProfile = aidReceipentProfile;
        this.organization = organization;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AidRecipientWorkArea = new javax.swing.JScrollPane();
        jSplitPane1 = new javax.swing.JSplitPane();
        AidRecipientOptionsJPanel = new javax.swing.JPanel();
        btnNewRequest = new javax.swing.JButton();
        btnHistory = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        AidReceipientWorkArea = new javax.swing.JPanel();

        jSplitPane1.setDividerLocation(150);

        btnNewRequest.setText("New Request");
        btnNewRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewRequestActionPerformed(evt);
            }
        });

        btnHistory.setText("History");
        btnHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistoryActionPerformed(evt);
            }
        });

        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AidRecipientOptionsJPanelLayout = new javax.swing.GroupLayout(AidRecipientOptionsJPanel);
        AidRecipientOptionsJPanel.setLayout(AidRecipientOptionsJPanelLayout);
        AidRecipientOptionsJPanelLayout.setHorizontalGroup(
            AidRecipientOptionsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AidRecipientOptionsJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AidRecipientOptionsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNewRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLogout))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        AidRecipientOptionsJPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnHistory, btnLogout, btnNewRequest});

        AidRecipientOptionsJPanelLayout.setVerticalGroup(
            AidRecipientOptionsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AidRecipientOptionsJPanelLayout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(btnNewRequest)
                .addGap(37, 37, 37)
                .addComponent(btnHistory)
                .addGap(32, 32, 32)
                .addComponent(btnLogout)
                .addContainerGap(189, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(AidRecipientOptionsJPanel);

        AidReceipientWorkArea.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(AidReceipientWorkArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 666, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistoryActionPerformed
        // TODO add your handling code here:
        AidReceipientHistoryJPanel arhpanel = new AidReceipientHistoryJPanel(userProcessContainer,aidReceipentProfile,organization);
        AidReceipientWorkArea.removeAll();
        AidReceipientWorkArea.add(arhpanel);
        CardLayout layout = (CardLayout) AidReceipientWorkArea.getLayout();
        layout.next(AidReceipientWorkArea);
    }//GEN-LAST:event_btnHistoryActionPerformed

    private void btnNewRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewRequestActionPerformed
        // TODO add your handling code here:
        AidReceipentNewRequestJPanel arnrpanel = new AidReceipentNewRequestJPanel(userProcessContainer,aidReceipentProfile,organization);
        AidReceipientWorkArea.removeAll();
        AidReceipientWorkArea.add(arnrpanel);
        CardLayout layout = (CardLayout) AidReceipientWorkArea.getLayout();
        layout.next(AidReceipientWorkArea);
    }//GEN-LAST:event_btnNewRequestActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this); 
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnLogoutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AidReceipientWorkArea;
    private javax.swing.JPanel AidRecipientOptionsJPanel;
    private javax.swing.JScrollPane AidRecipientWorkArea;
    private javax.swing.JButton btnHistory;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnNewRequest;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
