/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.MainProfilePages;

import DataConfiguration.Network;
import DataConfiguration.Organization;
import java.awt.CardLayout;
import javax.swing.JPanel;
import model.organization.AidReceipent.AidReceipentProfile;
import model.organization.DonationManagement.Donor;
import ui.AidReceipient.AidReceipentNewRequestJPanel;
import ui.AidReceipient.AidReceipientHistoryJPanel;

/**
 *
 * @author Sarthak
 */
public class AidRecipientJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    Network network;
    AidReceipentProfile aidReceipentProfile;
    Organization organization;
    /**
     * Creates new form VolunteerCoordinatorJPanel
     */
    public AidRecipientJPanel(JPanel userProcessContainer, Network network, AidReceipentProfile aidReceipentProfile, Organization organization) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.network = network;
        this.aidReceipentProfile = aidReceipentProfile;
        this.organization = organization;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AidRecipientWorkArea = new javax.swing.JScrollPane();
        jSplitPane1 = new javax.swing.JSplitPane();
        AidRecipientOptionsJPanel = new javax.swing.JPanel();
        btnNewRequest = new javax.swing.JButton();
        btnHistory = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        AidReceipientWorkArea = new javax.swing.JPanel();

        jSplitPane1.setDividerLocation(150);

        AidRecipientOptionsJPanel.setBackground(new java.awt.Color(0, 32, 41));
        AidRecipientOptionsJPanel.setPreferredSize(new java.awt.Dimension(238, 518));

        btnNewRequest.setFont(new java.awt.Font("Sora Medium", 0, 12)); // NOI18N
        btnNewRequest.setText("New Request");
        btnNewRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewRequestActionPerformed(evt);
            }
        });

        btnHistory.setFont(new java.awt.Font("Sora Medium", 0, 12)); // NOI18N
        btnHistory.setText("History");
        btnHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistoryActionPerformed(evt);
            }
        });

        btnLogout.setBackground(new java.awt.Color(255, 30, 0));
        btnLogout.setFont(new java.awt.Font("Sora Medium", 0, 12)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("Logout");
        btnLogout.setBorder(null);
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Sora ExtraBold", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("<html>Aid Coordinator Panel</html>");

        javax.swing.GroupLayout AidRecipientOptionsJPanelLayout = new javax.swing.GroupLayout(AidRecipientOptionsJPanel);
        AidRecipientOptionsJPanel.setLayout(AidRecipientOptionsJPanelLayout);
        AidRecipientOptionsJPanelLayout.setHorizontalGroup(
            AidRecipientOptionsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AidRecipientOptionsJPanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(AidRecipientOptionsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(AidRecipientOptionsJPanelLayout.createSequentialGroup()
                        .addGroup(AidRecipientOptionsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNewRequest, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE))
                        .addGap(69, 69, 69)))
                .addContainerGap())
        );

        AidRecipientOptionsJPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnLogout, btnNewRequest});

        AidRecipientOptionsJPanelLayout.setVerticalGroup(
            AidRecipientOptionsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AidRecipientOptionsJPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnNewRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 203, Short.MAX_VALUE)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        jSplitPane1.setLeftComponent(AidRecipientOptionsJPanel);

        AidReceipientWorkArea.setPreferredSize(new java.awt.Dimension(812, 557));
        AidReceipientWorkArea.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(AidReceipientWorkArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 812, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistoryActionPerformed
        // TODO add your handling code here:
        AidReceipientHistoryJPanel arhpanel = new AidReceipientHistoryJPanel(userProcessContainer,aidReceipentProfile,organization);
        AidReceipientWorkArea.removeAll();
        AidReceipientWorkArea.add(arhpanel);
        CardLayout layout = (CardLayout) AidReceipientWorkArea.getLayout();
        layout.next(AidReceipientWorkArea);   
    }//GEN-LAST:event_btnHistoryActionPerformed

    private void btnNewRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewRequestActionPerformed
        // TODO add your handling code here:
        AidReceipentNewRequestJPanel arnrpanel = new AidReceipentNewRequestJPanel(userProcessContainer,aidReceipentProfile,organization);
        AidReceipientWorkArea.removeAll();
        AidReceipientWorkArea.add(arnrpanel);
        CardLayout layout = (CardLayout) AidReceipientWorkArea.getLayout();
        layout.next(AidReceipientWorkArea);
    }//GEN-LAST:event_btnNewRequestActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this); 
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnLogoutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AidReceipientWorkArea;
    private javax.swing.JPanel AidRecipientOptionsJPanel;
    private javax.swing.JScrollPane AidRecipientWorkArea;
    private javax.swing.JButton btnHistory;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnNewRequest;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
