/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.MainProfilePages;

/**
 *
 * @author Sarthak
 */
public class AidRecipientJPanel extends javax.swing.JPanel {

    /**
     * Creates new form VolunteerCoordinatorJPanel
     */
    public AidRecipientJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        AidRecipientOptionsJPanel = new javax.swing.JPanel();
        btnAssit = new javax.swing.JButton();
        btnNeedAssitance = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        AidRecipientWorkArea = new javax.swing.JScrollPane();

        jSplitPane1.setDividerLocation(150);

        btnAssit.setText("Assist");

        btnNeedAssitance.setText("Nees Assistance");
        btnNeedAssitance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNeedAssitanceActionPerformed(evt);
            }
        });

        btnLogout.setText("Logout");

        javax.swing.GroupLayout AidRecipientOptionsJPanelLayout = new javax.swing.GroupLayout(AidRecipientOptionsJPanel);
        AidRecipientOptionsJPanel.setLayout(AidRecipientOptionsJPanelLayout);
        AidRecipientOptionsJPanelLayout.setHorizontalGroup(
            AidRecipientOptionsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AidRecipientOptionsJPanelLayout.createSequentialGroup()
                .addGroup(AidRecipientOptionsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AidRecipientOptionsJPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnAssit, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AidRecipientOptionsJPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnNeedAssitance, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AidRecipientOptionsJPanelLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(btnLogout)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AidRecipientOptionsJPanelLayout.setVerticalGroup(
            AidRecipientOptionsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AidRecipientOptionsJPanelLayout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(btnAssit)
                .addGap(37, 37, 37)
                .addComponent(btnNeedAssitance)
                .addGap(32, 32, 32)
                .addComponent(btnLogout)
                .addContainerGap(189, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(AidRecipientOptionsJPanel);
        jSplitPane1.setRightComponent(AidRecipientWorkArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 666, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnNeedAssitanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNeedAssitanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNeedAssitanceActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AidRecipientOptionsJPanel;
    private javax.swing.JScrollPane AidRecipientWorkArea;
    private javax.swing.JButton btnAssit;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnNeedAssitance;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
