/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.MainProfilePages;

import DataConfiguration.Network;
import java.awt.CardLayout;
import javax.swing.JPanel;
import model.organization.CamapignManagement.CampaignOrganizerProfile;
import ui.ProfileComponents.AddCampaignsJPanel;
import ui.ProfileComponents.VolunteerCoordinatorDashboard;

/**
 *
 * @author Sarthak
 */
public class CampaignOrganizerJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    Network network;
    CampaignOrganizerProfile campaignOrganizerProfile;
    
    /**
     * Creates new form VolunteerCoordinatorJPanel
     */
    public CampaignOrganizerJPanel(JPanel userProcessContainer, Network network, CampaignOrganizerProfile campaignOrganizerProfile) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.network = network;
        this.campaignOrganizerProfile = campaignOrganizerProfile;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        CampaignOrganizerJPanel = new javax.swing.JPanel();
        btnAddCampaigns = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnViewCampaigns = new javax.swing.JButton();
        CampaignOrganizerWorkArea = new javax.swing.JPanel();

        jSplitPane1.setDividerLocation(150);

        btnAddCampaigns.setText("Add Campaign");
        btnAddCampaigns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCampaignsActionPerformed(evt);
            }
        });

        btnLogout.setText("Logout");

        btnViewCampaigns.setText("View Campaign");

        javax.swing.GroupLayout CampaignOrganizerJPanelLayout = new javax.swing.GroupLayout(CampaignOrganizerJPanel);
        CampaignOrganizerJPanel.setLayout(CampaignOrganizerJPanelLayout);
        CampaignOrganizerJPanelLayout.setHorizontalGroup(
            CampaignOrganizerJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CampaignOrganizerJPanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(btnLogout)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CampaignOrganizerJPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(CampaignOrganizerJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnViewCampaigns, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAddCampaigns, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(36, 36, 36))
        );
        CampaignOrganizerJPanelLayout.setVerticalGroup(
            CampaignOrganizerJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CampaignOrganizerJPanelLayout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(btnAddCampaigns)
                .addGap(34, 34, 34)
                .addComponent(btnViewCampaigns)
                .addGap(53, 53, 53)
                .addComponent(btnLogout)
                .addContainerGap(185, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(CampaignOrganizerJPanel);

        CampaignOrganizerWorkArea.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(CampaignOrganizerWorkArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 666, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddCampaignsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCampaignsActionPerformed
        // TODO add your handling code here:
        AddCampaignsJPanel cowa = new AddCampaignsJPanel(CampaignOrganizerWorkArea, network);
           CampaignOrganizerWorkArea.add(cowa);
           CardLayout layout = (CardLayout) CampaignOrganizerWorkArea.getLayout();
           layout.next(CampaignOrganizerWorkArea);
    }//GEN-LAST:event_btnAddCampaignsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CampaignOrganizerJPanel;
    private javax.swing.JPanel CampaignOrganizerWorkArea;
    private javax.swing.JButton btnAddCampaigns;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnViewCampaigns;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
