/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.MainProfilePages;

/**
 *
 * @author Sarthak
 */
public class CampaignOrganizerJPanel extends javax.swing.JPanel {

    /**
     * Creates new form VolunteerCoordinatorJPanel
     */
    public CampaignOrganizerJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        CampaignOrganizerJPanel = new javax.swing.JPanel();
        btnAddCampaigns = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        CampaignOrganizerWorkArea = new javax.swing.JScrollPane();

        jSplitPane1.setDividerLocation(150);

        btnAddCampaigns.setText("Add Campaigns");

        btnLogout.setText("Logout");

        javax.swing.GroupLayout CampaignOrganizerJPanelLayout = new javax.swing.GroupLayout(CampaignOrganizerJPanel);
        CampaignOrganizerJPanel.setLayout(CampaignOrganizerJPanelLayout);
        CampaignOrganizerJPanelLayout.setHorizontalGroup(
            CampaignOrganizerJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CampaignOrganizerJPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAddCampaigns)
                .addGap(36, 36, 36))
            .addGroup(CampaignOrganizerJPanelLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(btnLogout)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        CampaignOrganizerJPanelLayout.setVerticalGroup(
            CampaignOrganizerJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CampaignOrganizerJPanelLayout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(btnAddCampaigns)
                .addGap(60, 60, 60)
                .addComponent(btnLogout)
                .addContainerGap(219, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(CampaignOrganizerJPanel);
        jSplitPane1.setRightComponent(CampaignOrganizerWorkArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 666, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CampaignOrganizerJPanel;
    private javax.swing.JScrollPane CampaignOrganizerWorkArea;
    private javax.swing.JButton btnAddCampaigns;
    private javax.swing.JButton btnLogout;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
