/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.MainProfilePages;

import DataConfiguration.Network;
import java.awt.CardLayout;
import javax.swing.JPanel;
import model.organization.CamapignManagement.CampaignOrganizerProfile;
import ui.ProfileComponents.AddCampaignsJPanel;
import ui.ProfileComponents.ViewCampaignsJPanel;
import ui.ProfileComponents.VolunteerCoordinatorDashboard;

/**
 *
 * @author Sarthak
 */
public class CampaignOrganizerJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    Network network;
    CampaignOrganizerProfile campaignOrganizerProfile;
    
    /**
     * Creates new form VolunteerCoordinatorJPanel
     */
    public CampaignOrganizerJPanel(JPanel userProcessContainer, Network network, CampaignOrganizerProfile campaignOrganizerProfile) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.network = network;
        this.campaignOrganizerProfile = campaignOrganizerProfile;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        CampaignOrganizerJPanel = new javax.swing.JPanel();
        btnAddCampaigns = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnViewCampaigns = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        CampaignOrganizerWorkArea = new javax.swing.JPanel();

        jSplitPane1.setDividerLocation(150);

        CampaignOrganizerJPanel.setBackground(new java.awt.Color(0, 32, 41));
        CampaignOrganizerJPanel.setMinimumSize(new java.awt.Dimension(238, 0));
        CampaignOrganizerJPanel.setPreferredSize(new java.awt.Dimension(238, 518));

        btnAddCampaigns.setFont(new java.awt.Font("Sora Medium", 0, 12)); // NOI18N
        btnAddCampaigns.setText("Add Campaign");
        btnAddCampaigns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCampaignsActionPerformed(evt);
            }
        });

        btnLogout.setBackground(new java.awt.Color(255, 30, 0));
        btnLogout.setFont(new java.awt.Font("Sora Medium", 0, 14)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("Logout");
        btnLogout.setBorder(null);
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnViewCampaigns.setFont(new java.awt.Font("Sora Medium", 0, 12)); // NOI18N
        btnViewCampaigns.setText("View Campaigns");
        btnViewCampaigns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewCampaignsActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Sora ExtraBold", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("<html>Campaign Organizer Panel</html>");

        javax.swing.GroupLayout CampaignOrganizerJPanelLayout = new javax.swing.GroupLayout(CampaignOrganizerJPanel);
        CampaignOrganizerJPanel.setLayout(CampaignOrganizerJPanelLayout);
        CampaignOrganizerJPanelLayout.setHorizontalGroup(
            CampaignOrganizerJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CampaignOrganizerJPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(CampaignOrganizerJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAddCampaigns, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnViewCampaigns, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                    .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        CampaignOrganizerJPanelLayout.setVerticalGroup(
            CampaignOrganizerJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CampaignOrganizerJPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAddCampaigns, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnViewCampaigns, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 226, Short.MAX_VALUE)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        jSplitPane1.setLeftComponent(CampaignOrganizerJPanel);

        CampaignOrganizerWorkArea.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(CampaignOrganizerWorkArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 877, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 582, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddCampaignsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCampaignsActionPerformed
        // TODO add your handling code here:
        AddCampaignsJPanel cowa = new AddCampaignsJPanel(CampaignOrganizerWorkArea, network);
           CampaignOrganizerWorkArea.add(cowa);
           CardLayout layout = (CardLayout) CampaignOrganizerWorkArea.getLayout();
           layout.next(CampaignOrganizerWorkArea);
    }//GEN-LAST:event_btnAddCampaignsActionPerformed

    private void btnViewCampaignsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewCampaignsActionPerformed
        // TODO add your handling code here:
        ViewCampaignsJPanel cowa = new ViewCampaignsJPanel(CampaignOrganizerWorkArea, network);
        CampaignOrganizerWorkArea.add(cowa);
        CardLayout layout = (CardLayout) CampaignOrganizerWorkArea.getLayout();
        layout.next(CampaignOrganizerWorkArea);
    }//GEN-LAST:event_btnViewCampaignsActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this); 
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnLogoutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CampaignOrganizerJPanel;
    private javax.swing.JPanel CampaignOrganizerWorkArea;
    private javax.swing.JButton btnAddCampaigns;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnViewCampaigns;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
