/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.MainProfilePages;

import DataConfiguration.Enterprise;
import DataConfiguration.Network;
import DataConfiguration.Organization;
import java.awt.CardLayout;
import javax.swing.JPanel;
import ui.DataAnalyst.ResourcesReportJPanel;
import ui.DataAnalyst.SeeReportJPanel;

/**
 *
 * @author Sarthak
 */
public class DataAnalystJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    Network network;
    Organization organization;
    /**
     * Creates new form VolunteerCoordinatorJPanel
     */
    public DataAnalystJPanel(JPanel userProcessContainer, Network network, Organization organization) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.network = network;
        this.organization = organization;
        
        Enterprise communityEnterprise = network.getEnterpriseDirectory().findEnterprise("Community Support Enterprise");
        this.organization = communityEnterprise.getOrganizationDirectory().findOrganization("Donation Management");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        DataAnalystOptionsJPanel = new javax.swing.JPanel();
        btnSeeReport = new javax.swing.JButton();
        btnResourcesReport = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        DataAnalystWorkArea = new javax.swing.JPanel();

        jSplitPane1.setDividerLocation(150);

        btnSeeReport.setText("See Report");
        btnSeeReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeeReportActionPerformed(evt);
            }
        });

        btnResourcesReport.setText("Resources Report");
        btnResourcesReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResourcesReportActionPerformed(evt);
            }
        });

        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DataAnalystOptionsJPanelLayout = new javax.swing.GroupLayout(DataAnalystOptionsJPanel);
        DataAnalystOptionsJPanel.setLayout(DataAnalystOptionsJPanelLayout);
        DataAnalystOptionsJPanelLayout.setHorizontalGroup(
            DataAnalystOptionsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DataAnalystOptionsJPanelLayout.createSequentialGroup()
                .addGroup(DataAnalystOptionsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DataAnalystOptionsJPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnSeeReport, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DataAnalystOptionsJPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnResourcesReport, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DataAnalystOptionsJPanelLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(btnLogout)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DataAnalystOptionsJPanelLayout.setVerticalGroup(
            DataAnalystOptionsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DataAnalystOptionsJPanelLayout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(btnSeeReport)
                .addGap(37, 37, 37)
                .addComponent(btnResourcesReport)
                .addGap(32, 32, 32)
                .addComponent(btnLogout)
                .addContainerGap(189, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(DataAnalystOptionsJPanel);

        DataAnalystWorkArea.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(DataAnalystWorkArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 666, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnResourcesReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResourcesReportActionPerformed
        // TODO add your handling code here:
        ResourcesReportJPanel rrJpanel = new ResourcesReportJPanel(userProcessContainer,network, organization);
        DataAnalystWorkArea.removeAll();
        DataAnalystWorkArea.add(rrJpanel);
        CardLayout layout = (CardLayout) DataAnalystWorkArea.getLayout();
        layout.next(DataAnalystWorkArea);
    }//GEN-LAST:event_btnResourcesReportActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this); 
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnSeeReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeeReportActionPerformed
        // TODO add your handling code here:
        SeeReportJPanel rrJpanel = new SeeReportJPanel(userProcessContainer,network, organization);
        DataAnalystWorkArea.removeAll();
        DataAnalystWorkArea.add(rrJpanel);
        CardLayout layout = (CardLayout) DataAnalystWorkArea.getLayout();
        layout.next(DataAnalystWorkArea);
    }//GEN-LAST:event_btnSeeReportActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DataAnalystOptionsJPanel;
    private javax.swing.JPanel DataAnalystWorkArea;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnResourcesReport;
    private javax.swing.JButton btnSeeReport;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
