/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.MainProfilePages;

/**
 *
 * @author Sarthak
 */
public class DataAnalystJPanel extends javax.swing.JPanel {

    /**
     * Creates new form VolunteerCoordinatorJPanel
     */
    public DataAnalystJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        DataAnalystOptionsJPanel = new javax.swing.JPanel();
        btnSeeReport = new javax.swing.JButton();
        btnResourcesReport = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        DataAnalystWorkArea = new javax.swing.JScrollPane();

        jSplitPane1.setDividerLocation(150);

        btnSeeReport.setText("See Report");

        btnResourcesReport.setText("Resources Report");
        btnResourcesReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResourcesReportActionPerformed(evt);
            }
        });

        btnLogout.setText("Logout");

        javax.swing.GroupLayout DataAnalystOptionsJPanelLayout = new javax.swing.GroupLayout(DataAnalystOptionsJPanel);
        DataAnalystOptionsJPanel.setLayout(DataAnalystOptionsJPanelLayout);
        DataAnalystOptionsJPanelLayout.setHorizontalGroup(
            DataAnalystOptionsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DataAnalystOptionsJPanelLayout.createSequentialGroup()
                .addGroup(DataAnalystOptionsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DataAnalystOptionsJPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnSeeReport, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DataAnalystOptionsJPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnResourcesReport, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DataAnalystOptionsJPanelLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(btnLogout)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DataAnalystOptionsJPanelLayout.setVerticalGroup(
            DataAnalystOptionsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DataAnalystOptionsJPanelLayout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(btnSeeReport)
                .addGap(37, 37, 37)
                .addComponent(btnResourcesReport)
                .addGap(32, 32, 32)
                .addComponent(btnLogout)
                .addContainerGap(189, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(DataAnalystOptionsJPanel);
        jSplitPane1.setRightComponent(DataAnalystWorkArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 666, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnResourcesReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResourcesReportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnResourcesReportActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DataAnalystOptionsJPanel;
    private javax.swing.JScrollPane DataAnalystWorkArea;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnResourcesReport;
    private javax.swing.JButton btnSeeReport;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
