/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.MainProfilePages;

/**
 *
 * @author Sarthak
 */
public class DonorJPanel extends javax.swing.JPanel {

    /**
     * Creates new form VolunteerCoordinatorJPanel
     */
    public DonorJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        DonorOptionsJPanel = new javax.swing.JPanel();
        btnDonateMoney = new javax.swing.JButton();
        btnDonateResources = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        DonarWorkArea = new javax.swing.JScrollPane();

        jSplitPane1.setDividerLocation(150);

        btnDonateMoney.setText("Donate Money");

        btnDonateResources.setText("Donate Resources");
        btnDonateResources.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDonateResourcesActionPerformed(evt);
            }
        });

        btnLogout.setText("Logout");

        javax.swing.GroupLayout DonorOptionsJPanelLayout = new javax.swing.GroupLayout(DonorOptionsJPanel);
        DonorOptionsJPanel.setLayout(DonorOptionsJPanelLayout);
        DonorOptionsJPanelLayout.setHorizontalGroup(
            DonorOptionsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DonorOptionsJPanelLayout.createSequentialGroup()
                .addGroup(DonorOptionsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DonorOptionsJPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnDonateMoney, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DonorOptionsJPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnDonateResources, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DonorOptionsJPanelLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(btnLogout)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DonorOptionsJPanelLayout.setVerticalGroup(
            DonorOptionsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DonorOptionsJPanelLayout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(btnDonateMoney)
                .addGap(37, 37, 37)
                .addComponent(btnDonateResources)
                .addGap(32, 32, 32)
                .addComponent(btnLogout)
                .addContainerGap(189, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(DonorOptionsJPanel);
        jSplitPane1.setRightComponent(DonarWorkArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 666, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDonateResourcesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDonateResourcesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDonateResourcesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane DonarWorkArea;
    private javax.swing.JPanel DonorOptionsJPanel;
    private javax.swing.JButton btnDonateMoney;
    private javax.swing.JButton btnDonateResources;
    private javax.swing.JButton btnLogout;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
