/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.MainProfilePages;

import DataConfiguration.Network;
import java.awt.CardLayout;
import javax.swing.JPanel;
import ui.LoginPageJPanel;
import ui.RegistrationPanels.AidReceipentRegistrationJPanel;
import ui.RegistrationPanels.DonorRegistrationJPanel;
import ui.RegistrationPanels.VolunteerRegistrationJPanel;

/**
 *
 * @author Sarthak
 */
public class RegistrationJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    Network network;
    /**
     * Creates new form RegistrationJPanel
     */
    public RegistrationJPanel(JPanel userProcessContainer, Network network) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.network = network;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        RegistrationOptionsJPanel = new javax.swing.JPanel();
        btnVolunteer = new javax.swing.JButton();
        btnDonor = new javax.swing.JButton();
        btnLoginPage = new javax.swing.JButton();
        btnRecipient = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        RegistrationWorkArea = new javax.swing.JPanel();

        jSplitPane1.setDividerLocation(170);

        RegistrationOptionsJPanel.setBackground(new java.awt.Color(0, 32, 41));
        RegistrationOptionsJPanel.setMinimumSize(new java.awt.Dimension(238, 0));
        RegistrationOptionsJPanel.setPreferredSize(new java.awt.Dimension(238, 518));

        btnVolunteer.setFont(new java.awt.Font("Sora Medium", 0, 12)); // NOI18N
        btnVolunteer.setText("Volunteer");
        btnVolunteer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolunteerActionPerformed(evt);
            }
        });

        btnDonor.setFont(new java.awt.Font("Sora Medium", 0, 12)); // NOI18N
        btnDonor.setText("Donor");
        btnDonor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDonorActionPerformed(evt);
            }
        });

        btnLoginPage.setBackground(new java.awt.Color(255, 30, 0));
        btnLoginPage.setFont(new java.awt.Font("Sora Medium", 0, 12)); // NOI18N
        btnLoginPage.setForeground(new java.awt.Color(255, 255, 255));
        btnLoginPage.setText("Login Page");
        btnLoginPage.setBorder(null);
        btnLoginPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginPageActionPerformed(evt);
            }
        });

        btnRecipient.setFont(new java.awt.Font("Sora Medium", 0, 12)); // NOI18N
        btnRecipient.setText("Recipient");
        btnRecipient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecipientActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Sora ExtraBold", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("<html>Registration</html>");

        javax.swing.GroupLayout RegistrationOptionsJPanelLayout = new javax.swing.GroupLayout(RegistrationOptionsJPanel);
        RegistrationOptionsJPanel.setLayout(RegistrationOptionsJPanelLayout);
        RegistrationOptionsJPanelLayout.setHorizontalGroup(
            RegistrationOptionsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegistrationOptionsJPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(RegistrationOptionsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnVolunteer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDonor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRecipient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLoginPage, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        RegistrationOptionsJPanelLayout.setVerticalGroup(
            RegistrationOptionsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegistrationOptionsJPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVolunteer, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDonor, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRecipient, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 145, Short.MAX_VALUE)
                .addComponent(btnLoginPage, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        jSplitPane1.setLeftComponent(RegistrationOptionsJPanel);

        RegistrationWorkArea.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(RegistrationWorkArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 721, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 531, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDonorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDonorActionPerformed
        // TODO add your handling code here:
        DonorRegistrationJPanel dnrjpanel = new DonorRegistrationJPanel(RegistrationWorkArea, network);
        RegistrationWorkArea.removeAll();
        RegistrationWorkArea.add(dnrjpanel);
        CardLayout layout = (CardLayout) RegistrationWorkArea.getLayout();
        layout.next(RegistrationWorkArea);
    }//GEN-LAST:event_btnDonorActionPerformed

    private void btnRecipientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecipientActionPerformed
        // TODO add your handling code here:
        AidReceipentRegistrationJPanel arjpanel = new AidReceipentRegistrationJPanel(RegistrationWorkArea, network);
        RegistrationWorkArea.removeAll();
        RegistrationWorkArea.add(arjpanel);
        CardLayout layout = (CardLayout) RegistrationWorkArea.getLayout();
        layout.next(RegistrationWorkArea);
    }//GEN-LAST:event_btnRecipientActionPerformed

    private void btnVolunteerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolunteerActionPerformed
        // TODO add your handling code here:
        VolunteerRegistrationJPanel vrjpanel = new VolunteerRegistrationJPanel(RegistrationWorkArea, network);
        RegistrationWorkArea.removeAll();
        RegistrationWorkArea.add(vrjpanel);
        CardLayout layout = (CardLayout) RegistrationWorkArea.getLayout();
        layout.next(RegistrationWorkArea);
    }//GEN-LAST:event_btnVolunteerActionPerformed

    private void btnLoginPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginPageActionPerformed
        // TODO add your handling code here:
        LoginPageJPanel lpjpanel = new LoginPageJPanel(userProcessContainer, network);
        userProcessContainer.add(lpjpanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnLoginPageActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel RegistrationOptionsJPanel;
    private javax.swing.JPanel RegistrationWorkArea;
    private javax.swing.JButton btnDonor;
    private javax.swing.JButton btnLoginPage;
    private javax.swing.JButton btnRecipient;
    private javax.swing.JButton btnVolunteer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
