/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.MainProfilePages;

import DataConfiguration.Network;
import java.awt.CardLayout;
import javax.swing.JPanel;
import ui.LoginPageJPanel;
import ui.RegistrationPanels.VolunteerRegistrationJPanel;

/**
 *
 * @author Sarthak
 */
public class RegistrationJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    Network network;
    /**
     * Creates new form RegistrationJPanel
     */
    public RegistrationJPanel(JPanel userProcessContainer, Network network) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.network = network;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        RegistrationOptionsJPanel = new javax.swing.JPanel();
        btnVolunteer = new javax.swing.JButton();
        btnDonor = new javax.swing.JButton();
        btnLoginPage = new javax.swing.JButton();
        btnRecipient = new javax.swing.JButton();
        RegistrationWorkArea = new javax.swing.JPanel();

        jSplitPane1.setDividerLocation(170);

        btnVolunteer.setText("Volunteer");
        btnVolunteer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolunteerActionPerformed(evt);
            }
        });

        btnDonor.setText("Donor");
        btnDonor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDonorActionPerformed(evt);
            }
        });

        btnLoginPage.setText("Login Page");
        btnLoginPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginPageActionPerformed(evt);
            }
        });

        btnRecipient.setText("Recipient");
        btnRecipient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecipientActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout RegistrationOptionsJPanelLayout = new javax.swing.GroupLayout(RegistrationOptionsJPanel);
        RegistrationOptionsJPanel.setLayout(RegistrationOptionsJPanelLayout);
        RegistrationOptionsJPanelLayout.setHorizontalGroup(
            RegistrationOptionsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegistrationOptionsJPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(RegistrationOptionsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnVolunteer, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                    .addComponent(btnDonor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRecipient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(32, 32, 32))
            .addGroup(RegistrationOptionsJPanelLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(btnLoginPage)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        RegistrationOptionsJPanelLayout.setVerticalGroup(
            RegistrationOptionsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegistrationOptionsJPanelLayout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(btnVolunteer)
                .addGap(27, 27, 27)
                .addComponent(btnDonor)
                .addGap(29, 29, 29)
                .addComponent(btnRecipient)
                .addGap(51, 51, 51)
                .addComponent(btnLoginPage)
                .addContainerGap(236, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(RegistrationOptionsJPanel);

        RegistrationWorkArea.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(RegistrationWorkArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 792, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDonorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDonorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDonorActionPerformed

    private void btnRecipientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecipientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRecipientActionPerformed

    private void btnVolunteerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolunteerActionPerformed
        // TODO add your handling code here:
        VolunteerRegistrationJPanel vrjpanel = new VolunteerRegistrationJPanel(RegistrationWorkArea, network);
        RegistrationWorkArea.removeAll();
        RegistrationWorkArea.add(vrjpanel);
        CardLayout layout = (CardLayout) RegistrationWorkArea.getLayout();
        layout.next(RegistrationWorkArea);
    }//GEN-LAST:event_btnVolunteerActionPerformed

    private void btnLoginPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginPageActionPerformed
        // TODO add your handling code here:
        LoginPageJPanel lpjpanel = new LoginPageJPanel(userProcessContainer, network);
        userProcessContainer.add(lpjpanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnLoginPageActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel RegistrationOptionsJPanel;
    private javax.swing.JPanel RegistrationWorkArea;
    private javax.swing.JButton btnDonor;
    private javax.swing.JButton btnLoginPage;
    private javax.swing.JButton btnRecipient;
    private javax.swing.JButton btnVolunteer;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
