/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.MainProfilePages;

import DataConfiguration.Network;
import java.awt.CardLayout;
import javax.swing.JPanel;
import model.organization.VolunteerManagement.VolunteerProfile;
import ui.ProfileComponents.ViewCampaignsJPanel;
import ui.ProfileComponents.ViewCampaignsOnVP;
import ui.ProfileComponents.VolunteerProfileUpdateJPanel;
import ui.ProfileComponents.VolunteerTasksJPanel;

/**
 *
 * @author Sarthak
 */
public class VolunteerJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    Network network;
    VolunteerProfile volunteerProfile;
    
    /**
     * Creates new form VolunteerJPanel
     */
    public VolunteerJPanel(JPanel userProcessContainer, Network network, VolunteerProfile volunteerProfile) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.network = network;
        this.volunteerProfile = volunteerProfile;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        VolunteerOptionsJPanel = new javax.swing.JPanel();
        btnViewTasks = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnProfile = new javax.swing.JButton();
        txtViewCampaigns = new javax.swing.JButton();
        VolunteerWorkArea = new javax.swing.JPanel();

        jSplitPane1.setDividerLocation(150);

        btnViewTasks.setText("View Tasks");
        btnViewTasks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewTasksActionPerformed(evt);
            }
        });

        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnProfile.setText("Profile");
        btnProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfileActionPerformed(evt);
            }
        });

        txtViewCampaigns.setText("View Campaigns");
        txtViewCampaigns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtViewCampaignsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout VolunteerOptionsJPanelLayout = new javax.swing.GroupLayout(VolunteerOptionsJPanel);
        VolunteerOptionsJPanel.setLayout(VolunteerOptionsJPanelLayout);
        VolunteerOptionsJPanelLayout.setHorizontalGroup(
            VolunteerOptionsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VolunteerOptionsJPanelLayout.createSequentialGroup()
                .addGroup(VolunteerOptionsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(VolunteerOptionsJPanelLayout.createSequentialGroup()
                        .addGroup(VolunteerOptionsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(VolunteerOptionsJPanelLayout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(btnViewTasks, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(VolunteerOptionsJPanelLayout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(btnLogout)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VolunteerOptionsJPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(VolunteerOptionsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtViewCampaigns, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnProfile, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        VolunteerOptionsJPanelLayout.setVerticalGroup(
            VolunteerOptionsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VolunteerOptionsJPanelLayout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(btnViewTasks)
                .addGap(28, 28, 28)
                .addComponent(txtViewCampaigns)
                .addGap(18, 18, 18)
                .addComponent(btnProfile)
                .addGap(56, 56, 56)
                .addComponent(btnLogout)
                .addContainerGap(104, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(VolunteerOptionsJPanel);

        VolunteerWorkArea.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(VolunteerWorkArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 719, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this); 
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnViewTasksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewTasksActionPerformed
        // TODO add your handling code here:
        VolunteerTasksJPanel vtjp = new VolunteerTasksJPanel(VolunteerWorkArea, network, volunteerProfile);
        VolunteerWorkArea.add(vtjp);
        CardLayout layout = (CardLayout) VolunteerWorkArea.getLayout();
        layout.next(VolunteerWorkArea);
    }//GEN-LAST:event_btnViewTasksActionPerformed

    private void btnProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfileActionPerformed
        // TODO add your handling code here:
        VolunteerProfileUpdateJPanel vtjp = new VolunteerProfileUpdateJPanel(VolunteerWorkArea, network, volunteerProfile);
        VolunteerWorkArea.add(vtjp);
        CardLayout layout = (CardLayout) VolunteerWorkArea.getLayout();
        layout.next(VolunteerWorkArea);
    }//GEN-LAST:event_btnProfileActionPerformed

    private void txtViewCampaignsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtViewCampaignsActionPerformed
        // TODO add your handling code here:
        ViewCampaignsOnVP vcjp = new ViewCampaignsOnVP(VolunteerWorkArea, network);
        VolunteerWorkArea.add(vcjp);
        CardLayout layout = (CardLayout) VolunteerWorkArea.getLayout();
        layout.next(VolunteerWorkArea);
    }//GEN-LAST:event_txtViewCampaignsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel VolunteerOptionsJPanel;
    private javax.swing.JPanel VolunteerWorkArea;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnProfile;
    private javax.swing.JButton btnViewTasks;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton txtViewCampaigns;
    // End of variables declaration//GEN-END:variables
}
