/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import DataConfiguration.Network;
import DataConfiguration.Organization;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.UserAccountManagement.UserAccount;
import model.UserAccountManagement.UserAccountDirectory;
import model.admin.AidCoordinator;
import model.admin.AdminProfile;
import model.organization.AidReceipent.AidReceipentProfile;
import model.organization.CamapignManagement.CampaignOrganizerProfile;
import model.organization.DataAnalyst.DataAnalystProfile;
import model.organization.VolunteerManagement.VolunteerCoordinator;
import model.organization.DonationManagement.Donor;
import model.organization.VolunteerManagement.VolunteerProfile;
import ui.AidDistribution.DistributionResourceJPanel;
import ui.MainProfilePages.AdminProfileJPanel;
import ui.MainProfilePages.AidCoordinatorJPanel;
import ui.MainProfilePages.AidRecipientJPanel;
import ui.MainProfilePages.CampaignOrganizerJPanel;
import ui.MainProfilePages.DataAnalystJPanel;

import ui.MainProfilePages.RegistrationJPanel;

import ui.MainProfilePages.VolunteerCoordinatorJPanel;


import ui.MainProfilePages.DonorJPanel;


import ui.MainProfilePages.VolunteerJPanel;


/**
 *
 * @author Sarthak
 */
public class LoginPageJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    Network network;
    /**
     * Creates new form LoginPageJPanel
     */
    public LoginPageJPanel(JPanel userProcessContainer, Network network) {
        initComponents();
        this.userProcessContainer = userProcessContainer;  
        this.network = network;
        setSize(870,600);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        txtPassword = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        lblTitle1 = new javax.swing.JLabel();
        lblTitle2 = new javax.swing.JLabel();
        btnRegister = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        lblTitle.setFont(new java.awt.Font("Sora ExtraBold", 1, 18)); // NOI18N
        lblTitle.setText("<html>Volunteer & Donation Management</html>");

        lblUsername.setText("Username:");

        lblPassword.setText("Password:");

        btnLogin.setBackground(new java.awt.Color(251, 248, 239));
        btnLogin.setFont(new java.awt.Font("Sora Medium", 0, 12)); // NOI18N
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        lblTitle1.setFont(new java.awt.Font("Sora ExtraBold", 1, 24)); // NOI18N
        lblTitle1.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle1.setText("<html>Register Now</html>");

        lblTitle2.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        lblTitle2.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle2.setText("<html>Join our community of volunteers, track your impact through a personalized dashboard, and connect with like-minded individuals. Sign up today to make a difference and be part of inspiring change!</html>");

        btnRegister.setFont(new java.awt.Font("Sora Medium", 0, 12)); // NOI18N
        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTitle2, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(lblTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTitle2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUsername)
                    .addComponent(lblPassword)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(lblUsername)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(lblPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(162, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:     
        UserAccountDirectory userAccountDirectory = network.getUserAccountDirectory();
        UserAccount userAccount = userAccountDirectory.AuthenticateUser(txtUsername.getText(), new String(txtPassword.getPassword()));
        
        if(userAccount == null){
            JOptionPane.showMessageDialog(null, "Username/Password invalid!","Warning",JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if(userAccount.getAssociatedPersonProfile().getRole().equals("Admin")){
           AdminProfile adminProfile = (AdminProfile) userAccount.getAssociatedPersonProfile();
           AdminProfileJPanel appanel = new AdminProfileJPanel(userProcessContainer, network, adminProfile);
           userProcessContainer.add(appanel);
           CardLayout layout = (CardLayout) userProcessContainer.getLayout();
           layout.next(userProcessContainer);
        }  
        if(userAccount.getAssociatedPersonProfile().getRole().equals("Volunteer")){
           VolunteerProfile volunteerProfile = (VolunteerProfile) userAccount.getAssociatedPersonProfile();
           VolunteerJPanel vjpanel = new VolunteerJPanel(userProcessContainer, network, volunteerProfile);
           userProcessContainer.add(vjpanel);
           CardLayout layout = (CardLayout) userProcessContainer.getLayout();
           layout.next(userProcessContainer);
        }  
        

        if(userAccount.getAssociatedPersonProfile().getRole().equals("Volunteer Coordinator")){
           VolunteerCoordinator volunteerCoordinatorProfile = (VolunteerCoordinator) userAccount.getAssociatedPersonProfile();
           VolunteerCoordinatorJPanel vcjpanel = new VolunteerCoordinatorJPanel(userProcessContainer, network, volunteerCoordinatorProfile);
           userProcessContainer.add(vcjpanel);
           CardLayout layout = (CardLayout) userProcessContainer.getLayout();
           layout.next(userProcessContainer);
        }
        
        if(userAccount.getAssociatedPersonProfile().getRole().equals("Campaign Organizer")){
           CampaignOrganizerProfile campaignOrganizerProfile = (CampaignOrganizerProfile) userAccount.getAssociatedPersonProfile();
           CampaignOrganizerJPanel cojpanel = new CampaignOrganizerJPanel(userProcessContainer, network, campaignOrganizerProfile);
           userProcessContainer.add(cojpanel);
           CardLayout layout = (CardLayout) userProcessContainer.getLayout();
           layout.next(userProcessContainer);
        }


        if(userAccount.getAssociatedPersonProfile().getRole().equals("Donor")){
           Donor donor = (Donor) userAccount.getAssociatedPersonProfile();
           DonorJPanel donorjpanel = new DonorJPanel(userProcessContainer, network, donor);
           userProcessContainer.add(donorjpanel);
           CardLayout layout = (CardLayout) userProcessContainer.getLayout();
           layout.next(userProcessContainer);
        }  
        if(userAccount.getAssociatedPersonProfile().getRole().equals("AidReceipent")){
           Organization organization = network.getEnterpriseDirectory().findEnterprise("Public Service Enterprise").getOrganizationDirectory().findOrganization("Receipient Registration");
           AidReceipentProfile aidReceipentProfile = (AidReceipentProfile) userAccount.getAssociatedPersonProfile();
           AidRecipientJPanel ajpanel = new AidRecipientJPanel(userProcessContainer, network, aidReceipentProfile,organization);
           userProcessContainer.add(ajpanel);
           CardLayout layout = (CardLayout) userProcessContainer.getLayout();
           layout.next(userProcessContainer);
        }  
        if(userAccount.getAssociatedPersonProfile().getRole().equals("Aid Coordinator")){
           Organization organization = network.getEnterpriseDirectory().findEnterprise("Non-Profit Enterprise").getOrganizationDirectory().findOrganization("Aid Distribution");
           AidCoordinator aidcoord = (AidCoordinator) userAccount.getAssociatedPersonProfile();
            AidCoordinatorJPanel acjpanel = new AidCoordinatorJPanel(userProcessContainer, network, aidcoord);
           userProcessContainer.add(acjpanel);
           CardLayout layout = (CardLayout) userProcessContainer.getLayout();
           layout.next(userProcessContainer);
        }
        if(userAccount.getAssociatedPersonProfile().getRole().equals("DataAnalyst")){
           Organization organization = network.getEnterpriseDirectory().findEnterprise("Corporate Donors Enterprise").getOrganizationDirectory().findOrganization("Analytics & Reporting");
           DataAnalystProfile dataAnalystProfile = (DataAnalystProfile) userAccount.getAssociatedPersonProfile();
           DataAnalystJPanel dapanel = new DataAnalystJPanel(userProcessContainer, network, organization);
           userProcessContainer.add(dapanel);
           CardLayout layout = (CardLayout) userProcessContainer.getLayout();
           layout.next(userProcessContainer);
        }  
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        // TODO add your handling code here:
        RegistrationJPanel regjpanel = new RegistrationJPanel(userProcessContainer, network);
        userProcessContainer.add(regjpanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnRegisterActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnRegister;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTitle1;
    private javax.swing.JLabel lblTitle2;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
