/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import DataConfiguration.Network;
import DataConfiguration.Organization;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.UserAccountManagement.UserAccount;
import model.UserAccountManagement.UserAccountDirectory;
import model.organization.AidReceipent.AidReceipentProfile;
import model.organization.CamapignManagement.CampaignOrganizerProfile;
import model.organization.VolunteerManagement.VolunteerCoordinator;
import model.organization.DonationManagement.Donor;
import model.organization.VolunteerManagement.VolunteerProfile;
import ui.MainProfilePages.AidRecipientJPanel;
import ui.MainProfilePages.CampaignOrganizerJPanel;

import ui.MainProfilePages.RegistrationJPanel;

import ui.MainProfilePages.VolunteerCoordinatorJPanel;


import ui.MainProfilePages.DonorJPanel;


import ui.MainProfilePages.VolunteerJPanel;


/**
 *
 * @author Sarthak
 */
public class LoginPageJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    Network network;
    /**
     * Creates new form LoginPageJPanel
     */
    public LoginPageJPanel(JPanel userProcessContainer, Network network) {
        initComponents();
        this.userProcessContainer = userProcessContainer;  
        this.network = network;
        setSize(870,600);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        txtPassword = new javax.swing.JPasswordField();
        btnRegister = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 102, 102));

        lblTitle.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        lblTitle.setText("Volunteer & Donation Management");

        lblUsername.setText("Username:");

        lblPassword.setText("Password:");

        btnLogin.setBackground(new java.awt.Color(251, 248, 239));
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(265, 265, 265)
                        .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(346, 346, 346)
                        .addComponent(btnLogin)
                        .addGap(60, 60, 60)
                        .addComponent(btnRegister))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(334, 334, 334)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPassword)
                                .addGap(33, 33, 33))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblUsername)
                                .addGap(38, 38, 38)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtUsername)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(257, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(lblTitle)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsername)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassword)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogin)
                    .addComponent(btnRegister))
                .addContainerGap(134, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:     
        UserAccountDirectory userAccountDirectory = network.getUserAccountDirectory();
        UserAccount userAccount = userAccountDirectory.AuthenticateUser(txtUsername.getText(), new String(txtPassword.getPassword()));
        
        if(userAccount == null){
            JOptionPane.showMessageDialog(null, "Username/Password invalid!","Warning",JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if(userAccount.getAssociatedPersonProfile().getRole().equals("Volunteer")){
           VolunteerProfile volunteerProfile = (VolunteerProfile) userAccount.getAssociatedPersonProfile();
           VolunteerJPanel vjpanel = new VolunteerJPanel(userProcessContainer, network, volunteerProfile);
           userProcessContainer.add(vjpanel);
           CardLayout layout = (CardLayout) userProcessContainer.getLayout();
           layout.next(userProcessContainer);
        }  
        

        if(userAccount.getAssociatedPersonProfile().getRole().equals("Volunteer Coordinator")){
           VolunteerCoordinator volunteerCoordinatorProfile = (VolunteerCoordinator) userAccount.getAssociatedPersonProfile();
           VolunteerCoordinatorJPanel vcjpanel = new VolunteerCoordinatorJPanel(userProcessContainer, network, volunteerCoordinatorProfile);
           userProcessContainer.add(vcjpanel);
           CardLayout layout = (CardLayout) userProcessContainer.getLayout();
           layout.next(userProcessContainer);
        }
        
        if(userAccount.getAssociatedPersonProfile().getRole().equals("Campaign Organizer")){
           CampaignOrganizerProfile campaignOrganizerProfile = (CampaignOrganizerProfile) userAccount.getAssociatedPersonProfile();
           CampaignOrganizerJPanel cojpanel = new CampaignOrganizerJPanel(userProcessContainer, network, campaignOrganizerProfile);
           userProcessContainer.add(cojpanel);
           CardLayout layout = (CardLayout) userProcessContainer.getLayout();
           layout.next(userProcessContainer);
        }


        if(userAccount.getAssociatedPersonProfile().getRole().equals("Donor")){
           Donor donor = (Donor) userAccount.getAssociatedPersonProfile();
           DonorJPanel donorjpanel = new DonorJPanel(userProcessContainer, network, donor);
           userProcessContainer.add(donorjpanel);
           CardLayout layout = (CardLayout) userProcessContainer.getLayout();
           layout.next(userProcessContainer);
        }  
        if(userAccount.getAssociatedPersonProfile().getRole().equals("AidReceipent")){
           Organization organization = network.getEnterpriseDirectory().findEnterprise("Public Service Enterprise").getOrganizationDirectory().findOrganization("Receipient Registration");
           AidReceipentProfile aidReceipentProfile = (AidReceipentProfile) userAccount.getAssociatedPersonProfile();
           AidRecipientJPanel ajpanel = new AidRecipientJPanel(userProcessContainer, network, aidReceipentProfile,organization);
           userProcessContainer.add(ajpanel);
           CardLayout layout = (CardLayout) userProcessContainer.getLayout();
           layout.next(userProcessContainer);
        }  
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        // TODO add your handling code here:
        RegistrationJPanel regjpanel = new RegistrationJPanel(userProcessContainer, network);
        userProcessContainer.add(regjpanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnRegisterActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnRegister;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
